/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controler.CNPJ;
import Controler.CPF;
import Controler.EmailValidador;
import java.util.regex.*;
import DAO.ClientesDAO;
import JavaBean.Clientes;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wramu
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
    }

    public void readJtableForDesc(String desc) {
        DefaultTableModel modelo = (DefaultTableModel) jTPesquisaUsuario.getModel();
        ClientesDAO udao = new ClientesDAO();
        try {
            for (Clientes p : udao.readForDesc(desc)) {

                modelo.addRow(new Object[]{
                    p.getIdClientes(),
                    p.getNome(),
                    p.getCpfCnpj(),
                    p.getTelefone(),
                    //p.getCelular(),
                    p.getEmail(), //p.getEndereco(),
                // p.getSetor(),
                //p.getCidade(),
                // p.getCep(),
                //p.getEstado(),
                //p.getDatacadastro()
                });

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblCadClienteNome = new javax.swing.JLabel();
        lblCadClienteTelefone = new javax.swing.JLabel();
        txtCadClienteNome = new javax.swing.JTextField();
        lblCadClienteCelular = new javax.swing.JLabel();
        lblCadClienteEndereco = new javax.swing.JLabel();
        txtCadClienteEndereco = new javax.swing.JTextField();
        lblCadClienteBairro = new javax.swing.JLabel();
        txtCadClienteBairro = new javax.swing.JTextField();
        lblCadClienteEstado = new javax.swing.JLabel();
        jtbCadClienteBarraFerramenta = new javax.swing.JToolBar();
        btnCadClienteSalvar = new javax.swing.JButton();
        btnCadClienteEditar = new javax.swing.JButton();
        btnCadClienteDelete = new javax.swing.JButton();
        btnCadClienteCancelar = new javax.swing.JButton();
        btnCadClienteAjudar = new javax.swing.JButton();
        lblCadClienteCep = new javax.swing.JLabel();
        lblCadClienteEmail = new javax.swing.JLabel();
        lblCadClienteDataCadastro = new javax.swing.JLabel();
        lblCadClienteCidade = new javax.swing.JLabel();
        txtCadClienteCidade = new javax.swing.JTextField();
        txtCadClienteCNPJ = new javax.swing.JFormattedTextField();
        txtCadClienteTelefone = new javax.swing.JFormattedTextField();
        txtCadClienteCelular = new javax.swing.JFormattedTextField();
        txtCadClienteCep = new javax.swing.JFormattedTextField();
        jbCadClienteEstado = new javax.swing.JComboBox();
        txtCadClienteDataCadastro = new javax.swing.JLabel();
        jbCadClienteCNPJ = new javax.swing.JComboBox();
        txtCadClienteEmail = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPesquisaUsuario = new javax.swing.JTable();
        lbPesquisarUsuariolBuscar = new javax.swing.JLabel();
        txtPesquisarUsuariolBuscar = new javax.swing.JTextField();
        btnPesquisarUsuarios = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblCadClienteNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadClienteNome.setText("*Nome:");
        lblCadClienteNome.setOpaque(true);

        lblCadClienteTelefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadClienteTelefone.setText("*Telefone:");
        lblCadClienteTelefone.setOpaque(true);

        txtCadClienteNome.setText(" ");
        txtCadClienteNome.setAutoscrolls(false);
        txtCadClienteNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadClienteNomeActionPerformed(evt);
            }
        });
        txtCadClienteNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCadClienteNomeKeyTyped(evt);
            }
        });

        lblCadClienteCelular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadClienteCelular.setText("Celular:");
        lblCadClienteCelular.setOpaque(true);

        lblCadClienteEndereco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadClienteEndereco.setText("Endereço:");
        lblCadClienteEndereco.setOpaque(true);

        txtCadClienteEndereco.setAutoscrolls(false);
        txtCadClienteEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadClienteEnderecoActionPerformed(evt);
            }
        });
        txtCadClienteEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCadClienteEnderecoKeyTyped(evt);
            }
        });

        lblCadClienteBairro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadClienteBairro.setText("Bairro:");
        lblCadClienteBairro.setOpaque(true);

        txtCadClienteBairro.setAutoscrolls(false);
        txtCadClienteBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadClienteBairroActionPerformed(evt);
            }
        });
        txtCadClienteBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCadClienteBairroKeyTyped(evt);
            }
        });

        lblCadClienteEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadClienteEstado.setText("Estado:");
        lblCadClienteEstado.setOpaque(true);

        jtbCadClienteBarraFerramenta.setFloatable(false);
        jtbCadClienteBarraFerramenta.setRollover(true);

        btnCadClienteSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/salvar.png"))); // NOI18N
        btnCadClienteSalvar.setText("Salvar");
        btnCadClienteSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadClienteSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadClienteSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadClienteSalvarActionPerformed(evt);
            }
        });
        jtbCadClienteBarraFerramenta.add(btnCadClienteSalvar);

        btnCadClienteEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit.png"))); // NOI18N
        btnCadClienteEditar.setText("Editar");
        btnCadClienteEditar.setFocusable(false);
        btnCadClienteEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadClienteEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadClienteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadClienteEditarActionPerformed(evt);
            }
        });
        jtbCadClienteBarraFerramenta.add(btnCadClienteEditar);

        btnCadClienteDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btnCadClienteDelete.setText("Excluir");
        btnCadClienteDelete.setFocusable(false);
        btnCadClienteDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadClienteDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadClienteDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadClienteDeleteActionPerformed(evt);
            }
        });
        jtbCadClienteBarraFerramenta.add(btnCadClienteDelete);

        btnCadClienteCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancelar.png"))); // NOI18N
        btnCadClienteCancelar.setText("Limpar");
        btnCadClienteCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadClienteCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadClienteCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadClienteCancelarActionPerformed(evt);
            }
        });
        jtbCadClienteBarraFerramenta.add(btnCadClienteCancelar);

        btnCadClienteAjudar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Help.png"))); // NOI18N
        btnCadClienteAjudar.setText("Ajuda");
        btnCadClienteAjudar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadClienteAjudar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadClienteAjudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadClienteAjudarActionPerformed(evt);
            }
        });
        jtbCadClienteBarraFerramenta.add(btnCadClienteAjudar);

        lblCadClienteCep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadClienteCep.setText("CEP:");
        lblCadClienteCep.setOpaque(true);

        lblCadClienteEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadClienteEmail.setText("*Email:");
        lblCadClienteEmail.setOpaque(true);

        lblCadClienteDataCadastro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadClienteDataCadastro.setText("Data de Cadastro:");
        lblCadClienteDataCadastro.setOpaque(true);

        lblCadClienteCidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadClienteCidade.setText("Cidade:");
        lblCadClienteCidade.setOpaque(true);

        txtCadClienteCidade.setText("Goiânia");
        txtCadClienteCidade.setAutoscrolls(false);
        txtCadClienteCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadClienteCidadeActionPerformed(evt);
            }
        });
        txtCadClienteCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCadClienteCidadeKeyTyped(evt);
            }
        });

        txtCadClienteCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadClienteCNPJActionPerformed(evt);
            }
        });

        try {
            txtCadClienteTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadClienteTelefone.setText("(62)");
        txtCadClienteTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadClienteTelefoneActionPerformed(evt);
            }
        });

        try {
            txtCadClienteCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadClienteCelular.setText("(62)");
        txtCadClienteCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadClienteCelularActionPerformed(evt);
            }
        });

        try {
            txtCadClienteCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadClienteCep.setText("");
        txtCadClienteCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadClienteCepActionPerformed(evt);
            }
        });

        jbCadClienteEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um Estado", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jbCadClienteEstado.setToolTipText("");
        jbCadClienteEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadClienteEstadoActionPerformed(evt);
            }
        });

        txtCadClienteDataCadastro.setText(" ");

        jbCadClienteCNPJ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "CPF", "CNPJ" }));
        jbCadClienteCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadClienteCNPJActionPerformed(evt);
            }
        });

        txtCadClienteEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadClienteEmailActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar Cliente"));

        jTPesquisaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CPF/CNPJ", "TELEFONE", "EMAIL"
            }
        ));
        jTPesquisaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPesquisaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTPesquisaUsuario);
        if (jTPesquisaUsuario.getColumnModel().getColumnCount() > 0) {
            jTPesquisaUsuario.getColumnModel().getColumn(0).setResizable(false);
            jTPesquisaUsuario.getColumnModel().getColumn(0).setPreferredWidth(40);
        }

        lbPesquisarUsuariolBuscar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPesquisarUsuariolBuscar.setText("Nome:");

        txtPesquisarUsuariolBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesquisarUsuariolBuscarKeyTyped(evt);
            }
        });

        btnPesquisarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/jobs.png"))); // NOI18N
        btnPesquisarUsuarios.setText("Pesquisar");
        btnPesquisarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbPesquisarUsuariolBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarUsuariolBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarUsuarios)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPesquisarUsuariolBuscar)
                    .addComponent(txtPesquisarUsuariolBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarUsuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtbCadClienteBarraFerramenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCadClienteBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCadClienteNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCadClienteTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(lblCadClienteEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCadClienteEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCadClienteCep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbCadClienteCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCadClienteBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCadClienteCep, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblCadClienteCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                            .addComponent(lblCadClienteEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jbCadClienteEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtCadClienteCidade))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtCadClienteNome, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCadClienteEndereco))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCadClienteEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCadClienteCNPJ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCadClienteTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCadClienteCelular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCadClienteDataCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCadClienteDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCadClienteCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbCadClienteBarraFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadClienteNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadClienteCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadClienteCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadClienteCelular)
                    .addComponent(lblCadClienteTelefone)
                    .addComponent(txtCadClienteTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCadClienteCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadClienteEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCadClienteDataCadastro)
                    .addComponent(txtCadClienteDataCadastro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadClienteEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadClienteEndereco))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadClienteBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadClienteBairro)
                    .addComponent(txtCadClienteCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadClienteCidade))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadClienteCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadClienteCep)
                    .addComponent(lblCadClienteEstado)
                    .addComponent(jbCadClienteEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCadClienteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadClienteNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadClienteNomeActionPerformed

    private void txtCadClienteBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadClienteBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadClienteBairroActionPerformed

    private void btnCadClienteSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadClienteSalvarActionPerformed
        // TODO add your handling code here:

        Clientes cadastrar = new Clientes();

        //Validaçao de Campos Nulos
        if ((txtCadClienteCNPJ.getText().isEmpty()) || (txtCadClienteEmail.getText().isEmpty()) || (txtCadClienteNome.getText().isEmpty()) || (txtCadClienteTelefone.getText().isEmpty()) ) {
            JOptionPane.showMessageDialog(null, "Preencha os Campos Obrigatórios");
            // Validacao de Email
        } else if (!(Pattern.matches(".+@.+\\.[a-z]+", txtCadClienteEmail.getText()))) {
            JOptionPane.showMessageDialog(null, "Informe um Email Valido", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            //cadastrar.setIdClientes(Integer.parseInt(txtCadClienteId.getText()+"")) ;
            cadastrar.setNome(txtCadClienteNome.getText());
            cadastrar.setCpfCnpj(txtCadClienteCNPJ.getText());
            cadastrar.setTelefone(txtCadClienteTelefone.getText());
            cadastrar.setCelular(txtCadClienteCelular.getText());
            cadastrar.setEmail(txtCadClienteEmail.getText());
            cadastrar.setEndereco(txtCadClienteEndereco.getText());
            cadastrar.setSetor(txtCadClienteBairro.getText());
            cadastrar.setEstado((String) jbCadClienteEstado.getSelectedItem());
            cadastrar.setCep(txtCadClienteCep.getText());
            cadastrar.setCidade(txtCadClienteCidade.getText());
            cadastrar.setDatacadastro(txtCadClienteDataCadastro.getText());
            
            //criando o objeto
            ClientesDAO dao = new ClientesDAO();

            try {
                dao.cadastrarCliente(cadastrar);
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                txtCadClienteCep.setText("");
                txtCadClienteCidade.setText("");
                txtCadClienteDataCadastro.setText("");
                txtCadClienteEmail.setText("");
                //txtCadClienteId.setText("");
                txtCadClienteNome.setText("");
                txtCadClienteCNPJ.setText("");
                txtCadClienteTelefone.setText("");
                txtCadClienteCelular.setText("");
                txtCadClienteEndereco.setText("");
                txtCadClienteBairro.setText("");
                jbCadClienteEstado.setSelectedItem("");
            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(null, "Erro ao cadastrar!" + ex);

            }
        }

        // Validaçao de CPF e CNPJ
        /*
        String cpfcnpj =null;
        if(jbCadClienteCNPJ.getSelectedIndex()==1){
            CPF pf = new CPF(cpfcnpj);
            if(pf.isCPF()){
            }else{
                JOptionPane.showMessageDialog(rootPane,"CPF inválido!");
            }
        }else{
            CNPJ pj = new CNPJ(cpfcnpj);
            if(pj.isCNPJ()){
            }else{
                JOptionPane.showMessageDialog(rootPane,"CNPJ inválido!");
            }
        }
         */

    }//GEN-LAST:event_btnCadClienteSalvarActionPerformed

    private void btnCadClienteCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadClienteCancelarActionPerformed
        // TODO add your handling code here:
        // Restriçao de Botoes
        btnCadClienteSalvar.setEnabled(true);
        btnCadClienteEditar.setEnabled(false);
        btnCadClienteDelete.setEnabled(false);
        btnCadClienteCancelar.setEnabled(false);
        //zera os valores
        txtCadClienteCep.setText("");
        txtCadClienteCidade.setText("");
        txtCadClienteDataCadastro.setText("");
        txtCadClienteEmail.setText("");
        //txtCadClienteId.setText("");
        txtCadClienteNome.setText("");
        txtCadClienteCNPJ.setText("");
        txtCadClienteTelefone.setText("");
        txtCadClienteCelular.setText("");
        txtCadClienteEndereco.setText("");
        txtCadClienteBairro.setText("");
        jbCadClienteEstado.setSelectedItem("");

    }//GEN-LAST:event_btnCadClienteCancelarActionPerformed

    private void btnCadClienteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadClienteEditarActionPerformed
        // TODO add your handling code here:
        // Restriçao de Botoes
        btnCadClienteSalvar.setEnabled(true);
        btnCadClienteEditar.setEnabled(false);
        btnCadClienteDelete.setEnabled(false);
        btnCadClienteCancelar.setEnabled(false);
        
        
        if (jTPesquisaUsuario.getSelectedRow() != -1) {
            Clientes p = new Clientes();
            ClientesDAO pdao = new ClientesDAO();

            p.setNome(txtCadClienteNome.getText());
            p.setCpfCnpj(txtCadClienteCNPJ.getText());
            p.setTelefone(txtCadClienteTelefone.getText());
            p.setCelular(txtCadClienteCelular.getText());
            p.setEmail(txtCadClienteEmail.getText());
            p.setEndereco(txtCadClienteEndereco.getText());
            p.setSetor(txtCadClienteBairro.getText());
            p.setEstado((String) jbCadClienteEstado.getSelectedItem());
            p.setCep(txtCadClienteCep.getText());
            p.setCidade(txtCadClienteCidade.getText());
            p.setIdClientes((int) jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 0));

            try {
                pdao.update(p);
                JOptionPane.showMessageDialog(null, "Editado com sucesso!");
                txtCadClienteCep.setText("");
                txtCadClienteCidade.setText("");
                //txtCadClienteDataCadastro.setText("");
                txtCadClienteEmail.setText("");
                //txtCadClienteId.setText("");
                txtCadClienteNome.setText("");
                txtCadClienteCNPJ.setText("");
                txtCadClienteTelefone.setText("");
                txtCadClienteCelular.setText("");
                txtCadClienteEndereco.setText("");
                txtCadClienteBairro.setText("");
                jbCadClienteEstado.setSelectedItem("");
            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(null, "Erro ao editar!" + ex);

            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um campo da tabela de pesquisa para editar!");
        }
    }//GEN-LAST:event_btnCadClienteEditarActionPerformed

    private void txtCadClienteCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadClienteCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadClienteCNPJActionPerformed

    private void txtCadClienteCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadClienteCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadClienteCepActionPerformed

    private void jbCadClienteEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadClienteEstadoActionPerformed
        // Mensagem de Erro caso não Selecione um Estado:
        int selestado = jbCadClienteEstado.getSelectedIndex();
        switch (selestado) {
            case 0:
                JOptionPane.showMessageDialog(rootPane, "Selecione um Estado");
                break;
        }
    }//GEN-LAST:event_jbCadClienteEstadoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Abre tela com Botoes desativados
        btnCadClienteEditar.setEnabled(false);
        btnCadClienteDelete.setEnabled(false);
        btnCadClienteCancelar.setEnabled(false); 
        // Pegar data do Pc para Sistema:
        java.util.Date data = new java.util.Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.MEDIUM);
        txtCadClienteDataCadastro.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void jbCadClienteCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadClienteCNPJActionPerformed
        // Mensagem de erro, Pegar Mascara CPF ou CNPJ:
        int selCnpj = jbCadClienteCNPJ.getSelectedIndex();
        txtCadClienteCNPJ.setValue(null);
        switch (selCnpj) {
            case 0:
                JOptionPane.showMessageDialog(rootPane, "Selecione um Tipo");
                break;
            case 1:
                txtCadClienteCNPJ.setFormatterFactory(CPF.getFormat());
                break;
            case 2:
                txtCadClienteCNPJ.setFormatterFactory(CNPJ.getFormat());
                break;
        }
    }//GEN-LAST:event_jbCadClienteCNPJActionPerformed

    private void txtCadClienteEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadClienteEmailActionPerformed
        // 

    }//GEN-LAST:event_txtCadClienteEmailActionPerformed

    private void btnCadClienteAjudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadClienteAjudarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"                                                                            OS GESTOR \n"
                                             + "Olá, precisa de ajuda?\n"
                                             +"\n"
                                             + "*Deseja salvar? Para isso primeiro preencha os campos abaixo em seguida salve o cadastro. \n"
                                             + "\n"
                                             + "*Deseja editar? Para isso é necessario que primeiro efetue a pesquisa,\n "
                                             + "selecione o funcionario para alteração e em seguinda faça a alteração de acordo com a necessidade.\n"
                                             + "\n"
                                             + "*Deseja excluir? Para excluir efetue a pesquisa pelo funcionario que deseja excluir, "
                                             
                                             + "selecione e exclua.\n "
                                             +"\n"
                                             +"*Deseja pesquisar? Para pesquisar digite no campo de pesquisa os dados desejados.\n"
                                             +"\n"
                                             +" *Digitou errado? basta acionar o botão limpar para limpar todos os campos.\n"
                                             +"\n");
        

        
    }//GEN-LAST:event_btnCadClienteAjudarActionPerformed

    private void jTPesquisaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPesquisaUsuarioMouseClicked
        // TODO add your handling code here:
        // Restriçao de Botoes e Telas
        btnCadClienteSalvar.setEnabled(false);
        btnCadClienteEditar.setEnabled(true);
        btnCadClienteDelete.setEnabled(true);
        btnCadClienteCancelar.setEnabled(true);
        
        
        CadastroUsuario pesquisa = new CadastroUsuario();
        if (jTPesquisaUsuario.getSelectedRow() != -1) {

            //campos txt 
            txtCadClienteNome.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 1).toString());
            txtCadClienteCNPJ.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 2).toString());
            txtCadClienteTelefone.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 3).toString());
            txtCadClienteEmail.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 4).toString());

            txtCadClienteCelular.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 4).toString());
            txtCadClienteEndereco.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 5).toString());
            /*txtCadClienteNome.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 1).toString());
            txtCadClienteNome.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 1).toString());
            txtCadClienteNome.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 1).toString());
            txtCadClienteNome.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 1).toString());
            txtCadClienteNome.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 1).toString());
            txtCadClienteNome.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 1).toString());
             */
        }
    }//GEN-LAST:event_jTPesquisaUsuarioMouseClicked

    private void btnPesquisarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarUsuariosActionPerformed
        // TODO add your handling code here:
        while (jTPesquisaUsuario.getRowCount() > 0) {
            DefaultTableModel dm = (DefaultTableModel) jTPesquisaUsuario.getModel();
            dm.getDataVector().removeAllElements();
        }
        DefaultTableModel modelo = (DefaultTableModel) jTPesquisaUsuario.getModel();

        readJtableForDesc(txtPesquisarUsuariolBuscar.getText());

        /*
        while(jTPesquisaUsuario.getRowCount() > 0) {
            readJtableForDesc(txtPesquisarUsuariolBuscar.getText());
            DefaultTableModel model = (DefaultTableModel) jTPesquisaUsuario.getModel();
            model.getDataVector().removeAllElements();
            UsuarioDAO udao = new UsuarioDAO();
            Usuario p = new Usuario();

            model.addRow(new Object[]{
                p.getIdusuario(),
                p.getLogin(),
                p.getSenha(),
                p.getIdfuncionario(),
                p.getIdpermissao()

            });

        }*/
    }//GEN-LAST:event_btnPesquisarUsuariosActionPerformed

    private void txtCadClienteEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadClienteEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadClienteEnderecoActionPerformed

    private void txtCadClienteCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadClienteCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadClienteCidadeActionPerformed

    private void txtCadClienteCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadClienteCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadClienteCelularActionPerformed

    private void btnCadClienteDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadClienteDeleteActionPerformed
        // TODO add your handling code here:
        // Restriçao de Botoes
        btnCadClienteSalvar.setEnabled(true);
        btnCadClienteEditar.setEnabled(false);
        btnCadClienteDelete.setEnabled(false);
        btnCadClienteCancelar.setEnabled(false);
        
        if (jTPesquisaUsuario.getSelectedRow() != -1) {
            Clientes p = new Clientes();
            ClientesDAO pdao = new ClientesDAO();

            p.setIdClientes((int) jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 0));

            try {
                pdao.delete(p);
                txtCadClienteCep.setText("");
                txtCadClienteCidade.setText("");
                txtCadClienteDataCadastro.setText("");
                txtCadClienteEmail.setText("");
                //txtCadClienteId.setText("");
                txtCadClienteNome.setText("");
                txtCadClienteCNPJ.setText("");
                txtCadClienteTelefone.setText("");
                txtCadClienteCelular.setText("");
                txtCadClienteEndereco.setText("");
                txtCadClienteBairro.setText("");
                jbCadClienteEstado.setSelectedItem("");
            } catch (SQLException ex) {
                Logger.getLogger(EstoqueCadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um item da tabela de pesquisa!");

        }
    }//GEN-LAST:event_btnCadClienteDeleteActionPerformed

    private void txtPesquisarUsuariolBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarUsuariolBuscarKeyTyped
        // TODO add your handling code here:
        int limite=40;
        if(txtPesquisarUsuariolBuscar.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtPesquisarUsuariolBuscarKeyTyped

    private void txtCadClienteNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadClienteNomeKeyTyped
        // Limita Caracteres 
        int limite=40;
        if(txtCadClienteNome.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtCadClienteNomeKeyTyped

    private void txtCadClienteBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadClienteBairroKeyTyped
       // Limita Caracteres 
       int limite=20;
        if(txtCadClienteBairro.getText().length()==limite){
            evt.consume();
        } 
    }//GEN-LAST:event_txtCadClienteBairroKeyTyped

    private void txtCadClienteCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadClienteCidadeKeyTyped
       // Limita Caracteres 
      int limite=20;
        if(txtCadClienteCidade.getText().length()==limite){
            evt.consume();
        }   
    }//GEN-LAST:event_txtCadClienteCidadeKeyTyped

    private void txtCadClienteEnderecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadClienteEnderecoKeyTyped
        // Limita Caracteres 
        int limite=60;
        if(txtCadClienteCidade.getText().length()==limite){
            evt.consume();
        }  
    }//GEN-LAST:event_txtCadClienteEnderecoKeyTyped

    private void txtCadClienteTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadClienteTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadClienteTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadClienteAjudar;
    private javax.swing.JButton btnCadClienteCancelar;
    private javax.swing.JButton btnCadClienteDelete;
    private javax.swing.JButton btnCadClienteEditar;
    private javax.swing.JButton btnCadClienteSalvar;
    private javax.swing.JButton btnPesquisarUsuarios;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTPesquisaUsuario;
    private javax.swing.JComboBox jbCadClienteCNPJ;
    private javax.swing.JComboBox jbCadClienteEstado;
    private javax.swing.JToolBar jtbCadClienteBarraFerramenta;
    private javax.swing.JLabel lbPesquisarUsuariolBuscar;
    private javax.swing.JLabel lblCadClienteBairro;
    private javax.swing.JLabel lblCadClienteCelular;
    private javax.swing.JLabel lblCadClienteCep;
    private javax.swing.JLabel lblCadClienteCidade;
    private javax.swing.JLabel lblCadClienteDataCadastro;
    private javax.swing.JLabel lblCadClienteEmail;
    private javax.swing.JLabel lblCadClienteEndereco;
    private javax.swing.JLabel lblCadClienteEstado;
    private javax.swing.JLabel lblCadClienteNome;
    private javax.swing.JLabel lblCadClienteTelefone;
    private javax.swing.JTextField txtCadClienteBairro;
    private javax.swing.JFormattedTextField txtCadClienteCNPJ;
    private javax.swing.JFormattedTextField txtCadClienteCelular;
    private javax.swing.JFormattedTextField txtCadClienteCep;
    private javax.swing.JTextField txtCadClienteCidade;
    private javax.swing.JLabel txtCadClienteDataCadastro;
    private javax.swing.JFormattedTextField txtCadClienteEmail;
    private javax.swing.JTextField txtCadClienteEndereco;
    private javax.swing.JTextField txtCadClienteNome;
    private javax.swing.JFormattedTextField txtCadClienteTelefone;
    private javax.swing.JTextField txtPesquisarUsuariolBuscar;
    // End of variables declaration//GEN-END:variables
}
