/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.FuncionarioDAO;
import JavaBean.Funcionario;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wramu
 */
public class CadastrarFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarFuncionario
     */
    public CadastrarFuncionario() {
        initComponents();
    }
    public void readJtableForDesc (String desc){
        DefaultTableModel modelo = (DefaultTableModel)jTPesquisaUsuario.getModel();
        FuncionarioDAO udao = new FuncionarioDAO();
        try {
            for (Funcionario p: udao.readForDesc(desc)) {
                
                modelo.addRow(new Object[]{
                    p.getIdfuncionario(),
                    p.getNome(),
                    p.getCpf(),
                    p.getCelular(),
                    p.getEmail()
                    
                    
                });
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadFuncionarioNome = new javax.swing.JLabel();
        lblCadFuncionarioRG = new javax.swing.JLabel();
        lblCadFuncionarioCPF = new javax.swing.JLabel();
        lblCadFuncionarioCelular = new javax.swing.JLabel();
        lblCadFuncionarioEndereco = new javax.swing.JLabel();
        lblCadFuncionarioBairro = new javax.swing.JLabel();
        txtCadFuncionarioBairro = new javax.swing.JTextField();
        lblCadFuncionarioEstado = new javax.swing.JLabel();
        lblCadFuncionarioTelefone = new javax.swing.JLabel();
        jtbCadClienteBarraFerramenta = new javax.swing.JToolBar();
        btnCadFuncionarioSalvar = new javax.swing.JButton();
        btnCadFuncionarioEditar = new javax.swing.JButton();
        btnCadFuncionarioDelete = new javax.swing.JButton();
        btnCadFuncionarioCancelar = new javax.swing.JButton();
        btnCadFuncionarioAjudar = new javax.swing.JButton();
        lblCadFuncionarioCidade = new javax.swing.JLabel();
        txtCadFuncionarioCidade = new javax.swing.JTextField();
        lblCadFuncionarioEmail = new javax.swing.JLabel();
        lblCadFuncionarioDTCadastro = new javax.swing.JLabel();
        lblCadFuncionarioSalario = new javax.swing.JLabel();
        lblCadFuncionarioFormacao = new javax.swing.JLabel();
        lblCadFuncionarioCadgo = new javax.swing.JLabel();
        lblCadFuncionarioCtps = new javax.swing.JLabel();
        txtCadFuncionarioFormacao = new javax.swing.JTextField();
        txtCadFuncionarioCPF = new javax.swing.JFormattedTextField();
        txtCadFuncionarioCelular = new javax.swing.JFormattedTextField();
        txtCadFuncionarioTelefone = new javax.swing.JFormattedTextField();
        txtCadFuncionarioCtps = new javax.swing.JFormattedTextField();
        txtCadFuncionarioEndereco = new javax.swing.JTextField();
        lblCadFuncionarioNCarteTraba = new javax.swing.JLabel();
        txtCadFuncionarioNCarteTraba = new javax.swing.JFormattedTextField();
        txtCadFuncionarioSalario = new javax.swing.JFormattedTextField();
        txtCadFuncionarioRG = new javax.swing.JFormattedTextField();
        lblCadFuncionarioCep = new javax.swing.JLabel();
        txtCadFuncionarioCep = new javax.swing.JFormattedTextField();
        jbCadFuncionarioEstado = new javax.swing.JComboBox();
        jbCadFuncionarioCargo = new javax.swing.JComboBox<String>();
        txtCadFuncionarioDTCadastro = new javax.swing.JLabel();
        txtCadFuncionarioEmail = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPesquisaUsuario = new javax.swing.JTable();
        lbPesquisarUsuariolBuscar = new javax.swing.JLabel();
        txtPesquisarUsuariolBuscar = new javax.swing.JTextField();
        btnPesquisarUsuarios = new javax.swing.JButton();
        txtCadFuncionarioNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionários");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblCadFuncionarioNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFuncionarioNome.setText("*Nome:");

        lblCadFuncionarioRG.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFuncionarioRG.setText("RG:");

        lblCadFuncionarioCPF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFuncionarioCPF.setText("*CPF:");
        lblCadFuncionarioCPF.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblCadFuncionarioCelular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFuncionarioCelular.setText("*Celular:");
        lblCadFuncionarioCelular.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblCadFuncionarioEndereco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFuncionarioEndereco.setText("Endereço:");

        lblCadFuncionarioBairro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFuncionarioBairro.setText("Bairro:");

        txtCadFuncionarioBairro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCadFuncionarioBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFuncionarioBairroActionPerformed(evt);
            }
        });
        txtCadFuncionarioBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCadFuncionarioBairroKeyTyped(evt);
            }
        });

        lblCadFuncionarioEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFuncionarioEstado.setText("Estado:");

        lblCadFuncionarioTelefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFuncionarioTelefone.setText("Telefone:");

        jtbCadClienteBarraFerramenta.setFloatable(false);
        jtbCadClienteBarraFerramenta.setRollover(true);

        btnCadFuncionarioSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/salvar.png"))); // NOI18N
        btnCadFuncionarioSalvar.setText("Salvar");
        btnCadFuncionarioSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadFuncionarioSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadFuncionarioSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFuncionarioSalvarActionPerformed(evt);
            }
        });
        jtbCadClienteBarraFerramenta.add(btnCadFuncionarioSalvar);

        btnCadFuncionarioEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit.png"))); // NOI18N
        btnCadFuncionarioEditar.setText("Editar");
        btnCadFuncionarioEditar.setFocusable(false);
        btnCadFuncionarioEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadFuncionarioEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadFuncionarioEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFuncionarioEditarActionPerformed(evt);
            }
        });
        jtbCadClienteBarraFerramenta.add(btnCadFuncionarioEditar);

        btnCadFuncionarioDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btnCadFuncionarioDelete.setText("Excluir");
        btnCadFuncionarioDelete.setFocusable(false);
        btnCadFuncionarioDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadFuncionarioDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadFuncionarioDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFuncionarioDeleteActionPerformed(evt);
            }
        });
        jtbCadClienteBarraFerramenta.add(btnCadFuncionarioDelete);

        btnCadFuncionarioCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancelar.png"))); // NOI18N
        btnCadFuncionarioCancelar.setText("Limpar");
        btnCadFuncionarioCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadFuncionarioCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadFuncionarioCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFuncionarioCancelarActionPerformed(evt);
            }
        });
        jtbCadClienteBarraFerramenta.add(btnCadFuncionarioCancelar);

        btnCadFuncionarioAjudar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Help.png"))); // NOI18N
        btnCadFuncionarioAjudar.setText("Ajuda");
        btnCadFuncionarioAjudar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadFuncionarioAjudar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadFuncionarioAjudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFuncionarioAjudarActionPerformed(evt);
            }
        });
        jtbCadClienteBarraFerramenta.add(btnCadFuncionarioAjudar);

        lblCadFuncionarioCidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFuncionarioCidade.setText("Cidade:");

        txtCadFuncionarioCidade.setText("Goiânia");
        txtCadFuncionarioCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFuncionarioCidadeActionPerformed(evt);
            }
        });
        txtCadFuncionarioCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCadFuncionarioCidadeKeyTyped(evt);
            }
        });

        lblCadFuncionarioEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFuncionarioEmail.setText("*Email:");

        lblCadFuncionarioDTCadastro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFuncionarioDTCadastro.setText("Data Cadastro:");

        lblCadFuncionarioSalario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFuncionarioSalario.setText("Salário:");
        lblCadFuncionarioSalario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblCadFuncionarioFormacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFuncionarioFormacao.setText("Formação:");
        lblCadFuncionarioFormacao.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblCadFuncionarioCadgo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFuncionarioCadgo.setText("Cargo:");

        lblCadFuncionarioCtps.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFuncionarioCtps.setText("PIS/PASEP:");

        txtCadFuncionarioFormacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCadFuncionarioFormacaoKeyTyped(evt);
            }
        });

        try {
            txtCadFuncionarioCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadFuncionarioCPF.setText("");
        txtCadFuncionarioCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFuncionarioCPFActionPerformed(evt);
            }
        });

        try {
            txtCadFuncionarioCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadFuncionarioCelular.setText("(62)");
        txtCadFuncionarioCelular.setToolTipText("");
        txtCadFuncionarioCelular.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCadFuncionarioCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFuncionarioCelularActionPerformed(evt);
            }
        });

        try {
            txtCadFuncionarioTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadFuncionarioTelefone.setText("(62)");
        txtCadFuncionarioTelefone.setToolTipText("");
        txtCadFuncionarioTelefone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCadFuncionarioTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFuncionarioTelefoneActionPerformed(evt);
            }
        });

        try {
            txtCadFuncionarioCtps.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.#####.##-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadFuncionarioCtps.setText("");
        txtCadFuncionarioCtps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFuncionarioCtpsActionPerformed(evt);
            }
        });

        txtCadFuncionarioEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFuncionarioEnderecoActionPerformed(evt);
            }
        });
        txtCadFuncionarioEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCadFuncionarioEnderecoKeyTyped(evt);
            }
        });

        lblCadFuncionarioNCarteTraba.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFuncionarioNCarteTraba.setText("Nº Carteira Trabalho:");
        lblCadFuncionarioNCarteTraba.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        try {
            txtCadFuncionarioNCarteTraba.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadFuncionarioNCarteTraba.setText("");
        txtCadFuncionarioNCarteTraba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFuncionarioNCarteTrabaActionPerformed(evt);
            }
        });

        txtCadFuncionarioSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtCadFuncionarioSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFuncionarioSalarioActionPerformed(evt);
            }
        });

        try {
            txtCadFuncionarioRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadFuncionarioRG.setText("");
        txtCadFuncionarioRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFuncionarioRGActionPerformed(evt);
            }
        });

        lblCadFuncionarioCep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFuncionarioCep.setText("CEP:");

        try {
            txtCadFuncionarioCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadFuncionarioCep.setText("");

        jbCadFuncionarioEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um estado", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jbCadFuncionarioEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadFuncionarioEstadoActionPerformed(evt);
            }
        });

        jbCadFuncionarioCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um cargo", "Administrador", "Ax Administrativo", "Ax Financeiro", "Gerente", "Técnico" }));
        jbCadFuncionarioCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadFuncionarioCargoActionPerformed(evt);
            }
        });

        txtCadFuncionarioDTCadastro.setText(" ");

        txtCadFuncionarioEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFuncionarioEmailActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar Funcionário"));

        jTPesquisaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CPF", "TELEFONE", "EMAIL"
            }
        ));
        jTPesquisaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPesquisaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTPesquisaUsuario);

        lbPesquisarUsuariolBuscar.setText("Nome:");

        txtPesquisarUsuariolBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarUsuariolBuscarActionPerformed(evt);
            }
        });
        txtPesquisarUsuariolBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesquisarUsuariolBuscarKeyTyped(evt);
            }
        });

        btnPesquisarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/jobs.png"))); // NOI18N
        btnPesquisarUsuarios.setText("Pesquisar");
        btnPesquisarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbPesquisarUsuariolBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarUsuariolBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarUsuarios)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPesquisarUsuariolBuscar)
                    .addComponent(txtPesquisarUsuariolBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarUsuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtCadFuncionarioNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFuncionarioNomeActionPerformed(evt);
            }
        });
        txtCadFuncionarioNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCadFuncionarioNomeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbCadClienteBarraFerramenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCadFuncionarioRG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCadFuncionarioTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCadFuncionarioCadgo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCadFuncionarioCtps, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(lblCadFuncionarioEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCadFuncionarioCep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCadFuncionarioBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCadFuncionarioNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCadFuncionarioEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCadFuncionarioEndereco)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbCadFuncionarioCargo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCadFuncionarioEmail)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCadFuncionarioBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCadFuncionarioCep, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCadFuncionarioCtps, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtCadFuncionarioRG, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtCadFuncionarioTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCadFuncionarioFormacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCadFuncionarioCelular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCadFuncionarioCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCadFuncionarioSalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCadFuncionarioNCarteTraba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtCadFuncionarioNCarteTraba, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                                .addComponent(txtCadFuncionarioSalario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                            .addComponent(txtCadFuncionarioFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtCadFuncionarioCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                                .addComponent(txtCadFuncionarioCPF, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGap(58, 58, 58))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblCadFuncionarioCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                            .addComponent(lblCadFuncionarioEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jbCadFuncionarioEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtCadFuncionarioCidade))
                                        .addGap(85, 85, 85))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCadFuncionarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCadFuncionarioDTCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCadFuncionarioDTCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jtbCadClienteBarraFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadFuncionarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadFuncionarioNome)
                    .addComponent(lblCadFuncionarioDTCadastro)
                    .addComponent(txtCadFuncionarioDTCadastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadFuncionarioCPF)
                    .addComponent(lblCadFuncionarioRG)
                    .addComponent(txtCadFuncionarioCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCadFuncionarioRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadFuncionarioCelular)
                    .addComponent(lblCadFuncionarioTelefone)
                    .addComponent(txtCadFuncionarioCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCadFuncionarioTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadFuncionarioEmail)
                    .addComponent(lblCadFuncionarioFormacao)
                    .addComponent(txtCadFuncionarioFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCadFuncionarioEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadFuncionarioCadgo)
                    .addComponent(lblCadFuncionarioSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCadFuncionarioSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadFuncionarioCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadFuncionarioCtps)
                    .addComponent(txtCadFuncionarioCtps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadFuncionarioNCarteTraba)
                    .addComponent(txtCadFuncionarioNCarteTraba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadFuncionarioEndereco)
                    .addComponent(txtCadFuncionarioEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadFuncionarioBairro)
                    .addComponent(txtCadFuncionarioBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadFuncionarioCidade)
                    .addComponent(txtCadFuncionarioCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadFuncionarioEstado)
                    .addComponent(lblCadFuncionarioCep)
                    .addComponent(txtCadFuncionarioCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadFuncionarioEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCadFuncionarioBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFuncionarioBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFuncionarioBairroActionPerformed

    private void btnCadFuncionarioSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFuncionarioSalvarActionPerformed

        //instru��es para cadastro
        //Validaçao de Campos Nulos
        if ((txtCadFuncionarioCPF.getText().isEmpty()) || (txtCadFuncionarioEmail.getText().isEmpty()) || (txtCadFuncionarioNome.getText().isEmpty()) || (txtCadFuncionarioCelular.getText().isEmpty()) ) {
            JOptionPane.showMessageDialog(null, "Preencha os Campos Obrigatórios");
        
        // Validacao de Email
        }else if (!(Pattern.matches(".+@.+\\.[a-z]+", txtCadFuncionarioEmail.getText()) )) {
            JOptionPane.showMessageDialog(null, "Informe um Email Valido", "Error", JOptionPane.ERROR_MESSAGE);
        } else 
        
        {

            Funcionario cadastrar = new Funcionario();
            cadastrar.setNome(txtCadFuncionarioNome.getText());
            cadastrar.setRg(txtCadFuncionarioRG.getText());
            cadastrar.setCpf(txtCadFuncionarioCPF.getText());
            cadastrar.setTelefone(txtCadFuncionarioTelefone.getText());
            cadastrar.setCelular(txtCadFuncionarioCelular.getText());
            cadastrar.setEmail(txtCadFuncionarioEmail.getText());
            cadastrar.setDataCadastro(txtCadFuncionarioDTCadastro.getText());
            cadastrar.setCargo((String) jbCadFuncionarioCargo.getSelectedItem());
            cadastrar.setFormacao(txtCadFuncionarioFormacao.getText());
            cadastrar.setSalario(txtCadFuncionarioSalario.getText());
            cadastrar.setCtps(txtCadFuncionarioCtps.getText());
            cadastrar.setNCarteTraba(txtCadFuncionarioNCarteTraba.getText());
            cadastrar.setEndereco(txtCadFuncionarioEndereco.getText());
            cadastrar.setBairro(txtCadFuncionarioBairro.getText());
            cadastrar.setCidade(txtCadFuncionarioCidade.getText());
            cadastrar.setEstado((String) jbCadFuncionarioEstado.getSelectedItem());
            cadastrar.setCep(txtCadFuncionarioCep.getText());

            FuncionarioDAO dao = new FuncionarioDAO();

            try {
                dao.cadastrarFuncionario(cadastrar);
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                
                //apagar campos ao salvar
                txtCadFuncionarioNome.setText("");
                txtCadFuncionarioCPF.setText("");
                txtCadFuncionarioRG.setText("");
                txtCadFuncionarioCelular.setText("");
                txtCadFuncionarioTelefone.setText("");
                txtCadFuncionarioEmail.setText("");
                //txtCadFuncionarioDTCadastro.setText("");
                jbCadFuncionarioCargo.setSelectedItem("");
                txtCadFuncionarioFormacao.setText("");
                txtCadFuncionarioSalario.setText("");
                txtCadFuncionarioCtps.setText("");
                txtCadFuncionarioNCarteTraba.setText("");
                txtCadFuncionarioEndereco.setText("");
                txtCadFuncionarioBairro.setText("");
                txtCadFuncionarioCidade.setText("");
                jbCadFuncionarioEstado.setSelectedItem("");
                txtCadFuncionarioCep.setText("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar!" + ex);

            }
        }


    }//GEN-LAST:event_btnCadFuncionarioSalvarActionPerformed

    private void btnCadFuncionarioCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFuncionarioCancelarActionPerformed
        // TODO add your handling code here:
        // Restriçao de Botoes
        btnCadFuncionarioSalvar.setEnabled(true);
        btnCadFuncionarioEditar.setEnabled(false);
        btnCadFuncionarioDelete.setEnabled(false);
        btnCadFuncionarioCancelar.setEnabled(false);
        //zera os valores
        txtCadFuncionarioNome.setText("");
        txtCadFuncionarioCPF.setText("");
        txtCadFuncionarioRG.setText("");
        txtCadFuncionarioCelular.setText("");
        txtCadFuncionarioTelefone.setText("");
        txtCadFuncionarioEmail.setText("");
        //txtCadFuncionarioDTCadastro.setText("");
        jbCadFuncionarioCargo.setSelectedItem("");
        txtCadFuncionarioFormacao.setText("");
        txtCadFuncionarioSalario.setText("");
        txtCadFuncionarioCtps.setText("");
        txtCadFuncionarioNCarteTraba.setText("");
        txtCadFuncionarioEndereco.setText("");
        txtCadFuncionarioBairro.setText("");
        txtCadFuncionarioCidade.setText("");
        jbCadFuncionarioEstado.setSelectedItem("");
        txtCadFuncionarioCep.setText("");

    }//GEN-LAST:event_btnCadFuncionarioCancelarActionPerformed

    private void txtCadFuncionarioCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFuncionarioCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFuncionarioCidadeActionPerformed

    private void txtCadFuncionarioTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFuncionarioTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFuncionarioTelefoneActionPerformed

    private void txtCadFuncionarioEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFuncionarioEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFuncionarioEnderecoActionPerformed

    private void txtCadFuncionarioCtpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFuncionarioCtpsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFuncionarioCtpsActionPerformed

    private void txtCadFuncionarioNCarteTrabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFuncionarioNCarteTrabaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFuncionarioNCarteTrabaActionPerformed

    private void jbCadFuncionarioEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadFuncionarioEstadoActionPerformed
        // Mensagem de Erro caso n�o Selecione um Estado:
        int selestado = jbCadFuncionarioEstado.getSelectedIndex();
         switch(selestado){
            case 0:
                JOptionPane.showMessageDialog(rootPane,"Selecione um Estado");
                break;
         }       
    }//GEN-LAST:event_jbCadFuncionarioEstadoActionPerformed

    private void btnCadFuncionarioAjudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFuncionarioAjudarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"                                                                            OS GESTOR \n"
                                             + "Olá, precisa de ajuda?\n"
                                             +"\n"
                                             + "*Deseja salvar? Para isso primeiro preencha os campos abaixo em seguida salve o cadastro. \n"
                                             + "\n"
                                             + "*Deseja editar? Para isso é necessario que primeiro efetue a pesquisa,\n "
                                             + "selecione o funcionario para alteração e em seguinda faça a alteração de acordo com a necessidade.\n"
                                             + "\n"
                                             + "*Deseja excluir? Para excluir efetue a pesquisa pelo funcionario que deseja excluir, "
                                             
                                             + "selecione e exclua.\n "
                                             +"\n"
                                             +"*Deseja pesquisar? Para pesquisar digite no campo de pesquisa os dados desejados.\n"
                                             +"\n"
                                             +" *Digitou errado? basta acionar o botão limpar para limpar todos os campos.\n"
                                             +"\n");
        
        
    }//GEN-LAST:event_btnCadFuncionarioAjudarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       // Abre tela com Botoes desativados
        btnCadFuncionarioEditar.setEnabled(false);
        btnCadFuncionarioDelete.setEnabled(false);
        btnCadFuncionarioCancelar.setEnabled(false); 
       // Puxa data do Pc para Sistema:
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.MEDIUM);
        txtCadFuncionarioDTCadastro.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void txtCadFuncionarioEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFuncionarioEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFuncionarioEmailActionPerformed

    private void jbCadFuncionarioCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadFuncionarioCargoActionPerformed
        // Mensagem de Erro caso nao Selecione um Cargo:
        int selcargo = jbCadFuncionarioCargo.getSelectedIndex();
         switch(selcargo){
            case 0:
                JOptionPane.showMessageDialog(rootPane,"Selecione um Cargo");
                break;
         }  
         

    }//GEN-LAST:event_jbCadFuncionarioCargoActionPerformed

    private void jTPesquisaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPesquisaUsuarioMouseClicked
        // TODO add your handling code here:
        // Restriçao de Botoes e Telas
        btnCadFuncionarioSalvar.setEnabled(false);
        btnCadFuncionarioEditar.setEnabled(true);
        btnCadFuncionarioDelete.setEnabled(true);
        btnCadFuncionarioCancelar.setEnabled(true);
        //txtPesquisarUsuariolBuscar.setEnabled(false);
        
        CadastroUsuario pesquisa = new CadastroUsuario();
        if (jTPesquisaUsuario.getSelectedRow() != -1) {

            //campos txt
            txtCadFuncionarioNome.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 1).toString());
            txtCadFuncionarioCPF.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 2).toString());
            txtCadFuncionarioCelular.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 3).toString());
            txtCadFuncionarioEmail.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 4).toString());

        }
    }//GEN-LAST:event_jTPesquisaUsuarioMouseClicked

    private void btnPesquisarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarUsuariosActionPerformed
        // TODO add your handling code here:
        while (jTPesquisaUsuario.getRowCount() > 0) {
            DefaultTableModel dm = (DefaultTableModel) jTPesquisaUsuario.getModel();
            dm.getDataVector().removeAllElements();
        }
        DefaultTableModel modelo = (DefaultTableModel)jTPesquisaUsuario.getModel();

        readJtableForDesc(txtPesquisarUsuariolBuscar.getText());

        /*
        while(jTPesquisaUsuario.getRowCount() > 0) {
            readJtableForDesc(txtPesquisarUsuariolBuscar.getText());
            DefaultTableModel model = (DefaultTableModel) jTPesquisaUsuario.getModel();
            model.getDataVector().removeAllElements();
            UsuarioDAO udao = new UsuarioDAO();
            Usuario p = new Usuario();

            model.addRow(new Object[]{
                p.getIdusuario(),
                p.getLogin(),
                p.getSenha(),
                p.getIdfuncionario(),
                p.getIdpermissao()

            });

        }*/
    }//GEN-LAST:event_btnPesquisarUsuariosActionPerformed

    private void btnCadFuncionarioEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFuncionarioEditarActionPerformed
        // TODO add your handling code here:
        // Restriçao de Botoes
        btnCadFuncionarioSalvar.setEnabled(true);
        btnCadFuncionarioEditar.setEnabled(false);
        btnCadFuncionarioDelete.setEnabled(false);
        btnCadFuncionarioCancelar.setEnabled(false);
        

        if (jTPesquisaUsuario.getSelectedRow() != -1) {
            Funcionario p = new Funcionario();
            FuncionarioDAO pdao = new FuncionarioDAO();

            p.setNome(txtCadFuncionarioNome.getText());
            p.setRg(txtCadFuncionarioRG.getText());
            p.setCpf(txtCadFuncionarioCPF.getText());
            p.setTelefone(txtCadFuncionarioTelefone.getText());
            p.setCelular(txtCadFuncionarioCelular.getText());
            p.setEmail(txtCadFuncionarioEmail.getText());
            //p.setDataCadastro(txtCadFuncionarioDTCadastro.getText());
            p.setCargo((String) jbCadFuncionarioCargo.getSelectedItem());
            p.setFormacao(txtCadFuncionarioFormacao.getText());
            p.setSalario(txtCadFuncionarioSalario.getText());
            p.setCtps(txtCadFuncionarioCtps.getText());
            p.setNCarteTraba(txtCadFuncionarioNCarteTraba.getText());
            p.setEndereco(txtCadFuncionarioEndereco.getText());
            p.setBairro(txtCadFuncionarioBairro.getText());
            p.setCidade(txtCadFuncionarioCidade.getText());
            p.setEstado((String) jbCadFuncionarioEstado.getSelectedItem());
            p.setCep(txtCadFuncionarioCep.getText());
            p.setIdfuncionario((int)jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 0));
            try {
                //p.setIdusuario((int)jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 0));
                pdao.update(p);
                txtCadFuncionarioNome.setText("");
                txtCadFuncionarioCPF.setText("");
                txtCadFuncionarioRG.setText("");
                txtCadFuncionarioCelular.setText("");
                txtCadFuncionarioTelefone.setText("");
                txtCadFuncionarioEmail.setText("");
                txtCadFuncionarioDTCadastro.setText("");
                jbCadFuncionarioCargo.setSelectedItem("");
                txtCadFuncionarioFormacao.setText("");
                txtCadFuncionarioSalario.setText("");
                txtCadFuncionarioCtps.setText("");
                txtCadFuncionarioNCarteTraba.setText("");
                txtCadFuncionarioEndereco.setText("");
                txtCadFuncionarioBairro.setText("");
                txtCadFuncionarioCidade.setText("");
                jbCadFuncionarioEstado.setSelectedItem("");
                txtCadFuncionarioCep.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(CadastrarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCadFuncionarioEditarActionPerformed

    private void btnCadFuncionarioDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFuncionarioDeleteActionPerformed
        // TODO add your handling code here:
        // Restriçao de Botoes
        btnCadFuncionarioSalvar.setEnabled(true);
        btnCadFuncionarioEditar.setEnabled(false);
        btnCadFuncionarioDelete.setEnabled(false);
        btnCadFuncionarioCancelar.setEnabled(false);
        
         if (jTPesquisaUsuario.getSelectedRow() != -1) {
            Funcionario p = new Funcionario();
            FuncionarioDAO pdao = new FuncionarioDAO();

            p.setIdfuncionario((int) jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 0));

             try {
                 pdao.delete(p);
                 txtCadFuncionarioNome.setText("");
                 txtCadFuncionarioCPF.setText("");
                 txtCadFuncionarioRG.setText("");
                 txtCadFuncionarioCelular.setText("");
                 txtCadFuncionarioTelefone.setText("");
                 txtCadFuncionarioEmail.setText("");
                 txtCadFuncionarioDTCadastro.setText("");
                 jbCadFuncionarioCargo.setSelectedItem("");
                 txtCadFuncionarioFormacao.setText("");
                 txtCadFuncionarioSalario.setText("");
                 txtCadFuncionarioCtps.setText("");
                 txtCadFuncionarioNCarteTraba.setText("");
                 txtCadFuncionarioEndereco.setText("");
                 txtCadFuncionarioBairro.setText("");
                 txtCadFuncionarioCidade.setText("");
                 jbCadFuncionarioEstado.setSelectedItem("");
                 txtCadFuncionarioCep.setText("");
             } catch (SQLException ex) {
                Logger.getLogger(EstoqueCadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
            }

            //JOptionPane.showMessageDialog(null, "Editado com sucesso!");
        }
    }//GEN-LAST:event_btnCadFuncionarioDeleteActionPerformed

    private void txtCadFuncionarioCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFuncionarioCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFuncionarioCPFActionPerformed

    private void txtCadFuncionarioCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFuncionarioCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFuncionarioCelularActionPerformed

    private void txtCadFuncionarioSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFuncionarioSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFuncionarioSalarioActionPerformed

    private void txtCadFuncionarioRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFuncionarioRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFuncionarioRGActionPerformed

    private void txtCadFuncionarioNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadFuncionarioNomeKeyTyped
        // TODO add your handling code here:
        int limite=40;
        if(txtCadFuncionarioNome.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtCadFuncionarioNomeKeyTyped

    private void txtCadFuncionarioFormacaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadFuncionarioFormacaoKeyTyped
        // TODO add your handling code here:
        int limite=20;
        if(txtCadFuncionarioFormacao.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtCadFuncionarioFormacaoKeyTyped

    private void txtCadFuncionarioBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadFuncionarioBairroKeyTyped
        // TODO add your handling code here:
        int limite=20;
        if(txtCadFuncionarioBairro.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtCadFuncionarioBairroKeyTyped

    private void txtCadFuncionarioNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFuncionarioNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFuncionarioNomeActionPerformed

    private void txtCadFuncionarioCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadFuncionarioCidadeKeyTyped
        // TODO add your handling code here:
        int limite=20;
        if(txtCadFuncionarioCidade.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtCadFuncionarioCidadeKeyTyped

    private void txtCadFuncionarioEnderecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadFuncionarioEnderecoKeyTyped
        // TODO add your handling code here:
        int limite=60;
        if(txtCadFuncionarioEndereco.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtCadFuncionarioEnderecoKeyTyped

    private void txtPesquisarUsuariolBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarUsuariolBuscarKeyTyped
        // TODO add your handling code here:
        int limite=40;
        if(txtPesquisarUsuariolBuscar.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtPesquisarUsuariolBuscarKeyTyped

    private void txtPesquisarUsuariolBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarUsuariolBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarUsuariolBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadFuncionarioAjudar;
    private javax.swing.JButton btnCadFuncionarioCancelar;
    private javax.swing.JButton btnCadFuncionarioDelete;
    private javax.swing.JButton btnCadFuncionarioEditar;
    private javax.swing.JButton btnCadFuncionarioSalvar;
    private javax.swing.JButton btnPesquisarUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTPesquisaUsuario;
    private javax.swing.JComboBox<String> jbCadFuncionarioCargo;
    private javax.swing.JComboBox jbCadFuncionarioEstado;
    private javax.swing.JToolBar jtbCadClienteBarraFerramenta;
    private javax.swing.JLabel lbPesquisarUsuariolBuscar;
    private javax.swing.JLabel lblCadFuncionarioBairro;
    private javax.swing.JLabel lblCadFuncionarioCPF;
    private javax.swing.JLabel lblCadFuncionarioCadgo;
    private javax.swing.JLabel lblCadFuncionarioCelular;
    private javax.swing.JLabel lblCadFuncionarioCep;
    private javax.swing.JLabel lblCadFuncionarioCidade;
    private javax.swing.JLabel lblCadFuncionarioCtps;
    private javax.swing.JLabel lblCadFuncionarioDTCadastro;
    private javax.swing.JLabel lblCadFuncionarioEmail;
    private javax.swing.JLabel lblCadFuncionarioEndereco;
    private javax.swing.JLabel lblCadFuncionarioEstado;
    private javax.swing.JLabel lblCadFuncionarioFormacao;
    private javax.swing.JLabel lblCadFuncionarioNCarteTraba;
    private javax.swing.JLabel lblCadFuncionarioNome;
    private javax.swing.JLabel lblCadFuncionarioRG;
    private javax.swing.JLabel lblCadFuncionarioSalario;
    private javax.swing.JLabel lblCadFuncionarioTelefone;
    private javax.swing.JTextField txtCadFuncionarioBairro;
    private javax.swing.JFormattedTextField txtCadFuncionarioCPF;
    private javax.swing.JFormattedTextField txtCadFuncionarioCelular;
    private javax.swing.JFormattedTextField txtCadFuncionarioCep;
    private javax.swing.JTextField txtCadFuncionarioCidade;
    private javax.swing.JFormattedTextField txtCadFuncionarioCtps;
    private javax.swing.JLabel txtCadFuncionarioDTCadastro;
    private javax.swing.JFormattedTextField txtCadFuncionarioEmail;
    private javax.swing.JTextField txtCadFuncionarioEndereco;
    private javax.swing.JTextField txtCadFuncionarioFormacao;
    private javax.swing.JFormattedTextField txtCadFuncionarioNCarteTraba;
    private javax.swing.JTextField txtCadFuncionarioNome;
    private javax.swing.JFormattedTextField txtCadFuncionarioRG;
    private javax.swing.JFormattedTextField txtCadFuncionarioSalario;
    private javax.swing.JFormattedTextField txtCadFuncionarioTelefone;
    private javax.swing.JTextField txtPesquisarUsuariolBuscar;
    // End of variables declaration//GEN-END:variables
}
