package View;

import DAO.FornecedorDAO;
import JavaBean.Fornecedor;
import java.sql.SQLException;
import java.text.DateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Walleson Moura
 */
public class CadastroFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form Fornecedor
     */
    public CadastroFornecedor() {
        initComponents();
    }
    public void readJtableForDesc (String desc){
        DefaultTableModel modelo = (DefaultTableModel)jTPesquisaUsuario.getModel();
       FornecedorDAO udao = new FornecedorDAO();
        try {
            for (Fornecedor p: udao.readForDesc(desc)) {
                
                modelo.addRow(new Object[]{
                    p.getId(),
                    p.getNome(),
                    p.getCnpj(),
                    p.getTelefone(),
                    //p.getCelular(),
                    p.getEmail(),
                    //p.getEndereco(),
                   // p.getSetor(),
                    //p.getCidade(),
                   // p.getCep(),
                    //p.getEstado(),
                    //p.getDatacadastro()
                    
                });
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadFornecedorNome = new javax.swing.JLabel();
        lblCadFornecedorCNPJ = new javax.swing.JLabel();
        lblCadFornecedorTelefone = new javax.swing.JLabel();
        txtCadFornecedorNome = new javax.swing.JTextField();
        lblCadFornecedorCelular = new javax.swing.JLabel();
        lblCadFornecedorEndereco = new javax.swing.JLabel();
        txtCadFornecedorEndereco = new javax.swing.JTextField();
        lblCadFornecedorCep = new javax.swing.JLabel();
        lblCadFornecedorBairro = new javax.swing.JLabel();
        lblCadFornecedorEmail = new javax.swing.JLabel();
        txtCadFornecedorBairro = new javax.swing.JTextField();
        lblCadFornecedorDataCadastro = new javax.swing.JLabel();
        lblCadFornecedorEstado = new javax.swing.JLabel();
        lblCadFornecedorCidade = new javax.swing.JLabel();
        txtCadFornecedorCidade = new javax.swing.JTextField();
        txtCadFornecedorCNPJ = new javax.swing.JFormattedTextField();
        txtCadFornecedorTelefone = new javax.swing.JFormattedTextField();
        txtCadFornecedorCelular = new javax.swing.JFormattedTextField();
        txtCadFornecedorCep = new javax.swing.JFormattedTextField();
        jbCadFornecedorEstado = new javax.swing.JComboBox();
        lblCadFornecedorNomeFantasia = new javax.swing.JLabel();
        txtCadFornecedorNomeFantasia = new javax.swing.JTextField();
        lblCadFornecedorInscEstadual = new javax.swing.JLabel();
        jtbFornecedorBarraFerramenta = new javax.swing.JToolBar();
        btnFornecedorSalvar = new javax.swing.JButton();
        btnFornecedorEditar = new javax.swing.JButton();
        btnFornecedorDelete = new javax.swing.JButton();
        btnFornecedorCancelar = new javax.swing.JButton();
        btnFornecedorAjuda = new javax.swing.JButton();
        txtCadFornecedorDataCadastro = new javax.swing.JLabel();
        txtCadFornecedorInscEstadual = new javax.swing.JFormattedTextField();
        txtCadFornecedorEmail = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPesquisaUsuario = new javax.swing.JTable();
        lbPesquisarUsuariolBuscar = new javax.swing.JLabel();
        txtPesquisarUsuariolBuscar = new javax.swing.JTextField();
        btnPesquisarUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Fornecedor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblCadFornecedorNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFornecedorNome.setText("*Razão Social:");
        lblCadFornecedorNome.setOpaque(true);

        lblCadFornecedorCNPJ.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFornecedorCNPJ.setText("*CNPJ:");
        lblCadFornecedorCNPJ.setOpaque(true);

        lblCadFornecedorTelefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFornecedorTelefone.setText("*Telefone:");
        lblCadFornecedorTelefone.setOpaque(true);

        txtCadFornecedorNome.setAutoscrolls(false);
        txtCadFornecedorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFornecedorNomeActionPerformed(evt);
            }
        });
        txtCadFornecedorNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCadFornecedorNomeKeyTyped(evt);
            }
        });

        lblCadFornecedorCelular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFornecedorCelular.setText("Celular:");
        lblCadFornecedorCelular.setOpaque(true);

        lblCadFornecedorEndereco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFornecedorEndereco.setText("Endereço:");
        lblCadFornecedorEndereco.setOpaque(true);

        txtCadFornecedorEndereco.setAutoscrolls(false);
        txtCadFornecedorEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCadFornecedorEnderecoKeyTyped(evt);
            }
        });

        lblCadFornecedorCep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFornecedorCep.setText("CEP:");
        lblCadFornecedorCep.setOpaque(true);

        lblCadFornecedorBairro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFornecedorBairro.setText("Bairro:");
        lblCadFornecedorBairro.setOpaque(true);

        lblCadFornecedorEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFornecedorEmail.setText("*Email:");
        lblCadFornecedorEmail.setOpaque(true);

        txtCadFornecedorBairro.setAutoscrolls(false);
        txtCadFornecedorBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFornecedorBairroActionPerformed(evt);
            }
        });
        txtCadFornecedorBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCadFornecedorBairroKeyTyped(evt);
            }
        });

        lblCadFornecedorDataCadastro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFornecedorDataCadastro.setText("Data de Cadastro:");
        lblCadFornecedorDataCadastro.setOpaque(true);

        lblCadFornecedorEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFornecedorEstado.setText("Estado:");
        lblCadFornecedorEstado.setOpaque(true);

        lblCadFornecedorCidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFornecedorCidade.setText("Cidade:");
        lblCadFornecedorCidade.setOpaque(true);

        txtCadFornecedorCidade.setText("Goiânia");
        txtCadFornecedorCidade.setAutoscrolls(false);
        txtCadFornecedorCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCadFornecedorCidadeKeyTyped(evt);
            }
        });

        try {
            txtCadFornecedorCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadFornecedorCNPJ.setText("");
        txtCadFornecedorCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFornecedorCNPJActionPerformed(evt);
            }
        });

        try {
            txtCadFornecedorTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadFornecedorTelefone.setText("(62)");

        try {
            txtCadFornecedorCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadFornecedorCelular.setText("(62)");

        try {
            txtCadFornecedorCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadFornecedorCep.setText("");
        txtCadFornecedorCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFornecedorCepActionPerformed(evt);
            }
        });

        jbCadFornecedorEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um estado", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jbCadFornecedorEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadFornecedorEstadoActionPerformed(evt);
            }
        });

        lblCadFornecedorNomeFantasia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFornecedorNomeFantasia.setText("Nome Fantasia:");

        txtCadFornecedorNomeFantasia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCadFornecedorNomeFantasiaKeyTyped(evt);
            }
        });

        lblCadFornecedorInscEstadual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadFornecedorInscEstadual.setText("Insc Estadual:");

        jtbFornecedorBarraFerramenta.setFloatable(false);
        jtbFornecedorBarraFerramenta.setRollover(true);

        btnFornecedorSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/salvar.png"))); // NOI18N
        btnFornecedorSalvar.setText("Salvar");
        btnFornecedorSalvar.setFocusable(false);
        btnFornecedorSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFornecedorSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFornecedorSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorSalvarActionPerformed(evt);
            }
        });
        jtbFornecedorBarraFerramenta.add(btnFornecedorSalvar);

        btnFornecedorEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit.png"))); // NOI18N
        btnFornecedorEditar.setText("Editar");
        btnFornecedorEditar.setFocusable(false);
        btnFornecedorEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFornecedorEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFornecedorEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorEditarActionPerformed(evt);
            }
        });
        jtbFornecedorBarraFerramenta.add(btnFornecedorEditar);

        btnFornecedorDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btnFornecedorDelete.setText("Excluir");
        btnFornecedorDelete.setFocusable(false);
        btnFornecedorDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFornecedorDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFornecedorDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorDeleteActionPerformed(evt);
            }
        });
        jtbFornecedorBarraFerramenta.add(btnFornecedorDelete);

        btnFornecedorCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancelar.png"))); // NOI18N
        btnFornecedorCancelar.setText("Limpar");
        btnFornecedorCancelar.setFocusable(false);
        btnFornecedorCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFornecedorCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFornecedorCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorCancelarActionPerformed(evt);
            }
        });
        jtbFornecedorBarraFerramenta.add(btnFornecedorCancelar);

        btnFornecedorAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Help.png"))); // NOI18N
        btnFornecedorAjuda.setText("Ajuda");
        btnFornecedorAjuda.setFocusable(false);
        btnFornecedorAjuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFornecedorAjuda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFornecedorAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorAjudaActionPerformed(evt);
            }
        });
        jtbFornecedorBarraFerramenta.add(btnFornecedorAjuda);

        txtCadFornecedorDataCadastro.setText(" ");

        try {
            txtCadFornecedorInscEstadual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadFornecedorInscEstadual.setText("");

        txtCadFornecedorEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFornecedorEmailActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar Fornecedor"));

        jTPesquisaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CNPJ", "TELEFONE", "EMAIL"
            }
        ));
        jTPesquisaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPesquisaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTPesquisaUsuario);

        lbPesquisarUsuariolBuscar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPesquisarUsuariolBuscar.setText("Nome:");

        txtPesquisarUsuariolBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarUsuariolBuscarActionPerformed(evt);
            }
        });
        txtPesquisarUsuariolBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesquisarUsuariolBuscarKeyTyped(evt);
            }
        });

        btnPesquisarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/jobs.png"))); // NOI18N
        btnPesquisarUsuarios.setText("Pesquisar");
        btnPesquisarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbPesquisarUsuariolBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarUsuariolBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarUsuarios)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPesquisarUsuariolBuscar)
                    .addComponent(txtPesquisarUsuariolBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarUsuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCadFornecedorBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(lblCadFornecedorCep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCadFornecedorBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCadFornecedorCep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblCadFornecedorCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCadFornecedorCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCadFornecedorDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCadFornecedorCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCadFornecedorInscEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCadFornecedorDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCadFornecedorCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(txtCadFornecedorInscEstadual)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblCadFornecedorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCadFornecedorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCadFornecedorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCadFornecedorCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCadFornecedorNome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCadFornecedorCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCadFornecedorNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadFornecedorNomeFantasia))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCadFornecedorEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCadFornecedorEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCadFornecedorTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(txtCadFornecedorEndereco))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCadFornecedorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCadFornecedorTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jtbFornecedorBarraFerramenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbFornecedorBarraFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadFornecedorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadFornecedorNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadFornecedorNomeFantasia)
                    .addComponent(txtCadFornecedorNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCadFornecedorInscEstadual)
                        .addComponent(txtCadFornecedorInscEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCadFornecedorCNPJ)
                        .addComponent(lblCadFornecedorCNPJ)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCadFornecedorCelular)
                    .addComponent(lblCadFornecedorCelular)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCadFornecedorTelefone)
                        .addComponent(lblCadFornecedorTelefone)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadFornecedorEmail)
                    .addComponent(lblCadFornecedorDataCadastro)
                    .addComponent(txtCadFornecedorDataCadastro)
                    .addComponent(txtCadFornecedorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadFornecedorEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadFornecedorEndereco))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadFornecedorBairro)
                    .addComponent(txtCadFornecedorBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadFornecedorCidade)
                    .addComponent(txtCadFornecedorCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadFornecedorEstado)
                    .addComponent(txtCadFornecedorCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadFornecedorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadFornecedorCep))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Caastro Fornecedor");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCadFornecedorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFornecedorNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFornecedorNomeActionPerformed

    private void txtCadFornecedorBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFornecedorBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFornecedorBairroActionPerformed

    private void txtCadFornecedorCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFornecedorCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFornecedorCNPJActionPerformed

    private void txtCadFornecedorCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFornecedorCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFornecedorCepActionPerformed

    private void jbCadFornecedorEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadFornecedorEstadoActionPerformed
        // Mensagem de Erro caso não Selecione um Estado:
        int selestado = jbCadFornecedorEstado.getSelectedIndex();
         switch(selestado){
            case 0:
                JOptionPane.showMessageDialog(rootPane,"Selecione um Estado");
                break;
         }       
    }//GEN-LAST:event_jbCadFornecedorEstadoActionPerformed

    private void btnFornecedorSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorSalvarActionPerformed
        // TODO add your handling code here:
         //Validaçao de Campos Nulos
        if ((txtCadFornecedorCNPJ.getText().isEmpty()) || (txtCadFornecedorEmail.getText().isEmpty()) || (txtCadFornecedorNome.getText().isEmpty()) || (txtCadFornecedorTelefone.getText().isEmpty()) ) {
            JOptionPane.showMessageDialog(null, "Preencha os Campos Obrigatórios");
            
        
        } else if (!(Pattern.matches(".+@.+\\.[a-z]+", txtCadFornecedorEmail.getText())))
            { JOptionPane.showMessageDialog(null, "Informe um Email Valido", "Error", JOptionPane.ERROR_MESSAGE);
        } else{
        Fornecedor cadastrar = new Fornecedor();
        cadastrar.setNome(txtCadFornecedorNome.getText());
        cadastrar.setNomeFantasia(txtCadFornecedorNomeFantasia.getText());
        cadastrar.setCnpj(txtCadFornecedorCNPJ.getText());
        cadastrar.setInEstadual(txtCadFornecedorInscEstadual.getText());
        cadastrar.setTelefone(txtCadFornecedorTelefone.getText());
        cadastrar.setCelular(txtCadFornecedorCelular.getText());
        cadastrar.setEmail(txtCadFornecedorEmail.getText());
        cadastrar.setDataCadastro(txtCadFornecedorDataCadastro.getText());
        cadastrar.setEndereco(txtCadFornecedorEndereco.getText());
        cadastrar.setBairro(txtCadFornecedorBairro.getText());
        cadastrar.setCidade(txtCadFornecedorCidade.getText());
        cadastrar.setCep(txtCadFornecedorCep.getText());
        cadastrar.setEstado((String)jbCadFornecedorEstado.getSelectedItem());
        FornecedorDAO dao = new FornecedorDAO();
        
        
        try {
            dao.cadastrarFornecedor(cadastrar);
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
            //apagar campos ao salvar
            txtCadFornecedorNome.setText("");
            txtCadFornecedorNomeFantasia.setText("");
            txtCadFornecedorCNPJ.setText("");
            txtCadFornecedorInscEstadual.setText("");
            txtCadFornecedorTelefone.setText("");
            txtCadFornecedorCelular.setText("");
            txtCadFornecedorDataCadastro.setText("");
            txtCadFornecedorEndereco.setText("");
            txtCadFornecedorBairro.setText("");
            txtCadFornecedorCidade.setText("");
            txtCadFornecedorCep.setText("");
            jbCadFornecedorEstado.setSelectedItem("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar!" +ex);
            
        }
        }
        
        
    }//GEN-LAST:event_btnFornecedorSalvarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Abre tela com Botoes desativados
        btnFornecedorEditar.setEnabled(false);
        btnFornecedorDelete.setEnabled(false);
        btnFornecedorCancelar.setEnabled(false);
        
        // Pega Data Sistema
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.MEDIUM);
        txtCadFornecedorDataCadastro.setText(formatador.format(data));
        
    }//GEN-LAST:event_formWindowActivated

    private void btnFornecedorCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorCancelarActionPerformed
         // TODO add your handling code here:
        // Restriçao de Botoes
        btnFornecedorSalvar.setEnabled(true);
        btnFornecedorEditar.setEnabled(false);
        btnFornecedorDelete.setEnabled(false);
        btnFornecedorCancelar.setEnabled(false);
        txtPesquisarUsuariolBuscar.setEnabled(true);
        
        //zera os valores
        txtCadFornecedorBairro.setText("");
        txtCadFornecedorCNPJ.setText("");
        txtCadFornecedorCelular.setText("");
        txtCadFornecedorCep.setText("");
        txtCadFornecedorCidade.setText("");
        txtCadFornecedorEmail.setText("");
        txtCadFornecedorEndereco.setText("");
        txtCadFornecedorInscEstadual.setText("");
        txtCadFornecedorNome.setText("");
        txtCadFornecedorNomeFantasia.setText("");
        txtCadFornecedorTelefone.setText("");
        
        
        
       

    }//GEN-LAST:event_btnFornecedorCancelarActionPerformed

    private void txtCadFornecedorEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFornecedorEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFornecedorEmailActionPerformed

    private void btnFornecedorAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorAjudaActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,"                                                                            OS GESTOR \n"
                                             + "Olá, precisa de ajuda?\n"
                                             +"\n"
                                             + "*Deseja salvar? Para isso primeiro preencha os campos abaixo em seguida salve o cadastro. \n"
                                             + "\n"
                                             + "*Deseja editar? Para isso é necessario que primeiro efetue a pesquisa,\n "
                                             + "selecione o funcionario para alteração e em seguinda faça a alteração de acordo com a necessidade.\n"
                                             + "\n"
                                             + "*Deseja excluir? Para excluir efetue a pesquisa pelo funcionario que deseja excluir, "
                                             
                                              + "selecione e exclua.\n "
                                             +"\n"
                                             +"*Deseja pesquisar? Para pesquisar digite no campo de pesquisa os dados desejados.\n"
                                             +"\n"
                                             +" *Digitou errado? basta acionar o botão limpar para limpar todos os campos.\n"
                                             +"\n");
    }//GEN-LAST:event_btnFornecedorAjudaActionPerformed

    private void jTPesquisaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPesquisaUsuarioMouseClicked
            // Restriçao de Botoes
            btnFornecedorSalvar.setEnabled(false);
            btnFornecedorEditar.setEnabled(true);
            btnFornecedorDelete.setEnabled(true);
            btnFornecedorCancelar.setEnabled(true);
            txtPesquisarUsuariolBuscar.setEnabled(false);
            
        CadastroUsuario pesquisa = new CadastroUsuario();
        if(jTPesquisaUsuario.getSelectedRow() != -1){

            //campos txt

            txtCadFornecedorNome.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 1).toString());
            txtCadFornecedorCNPJ.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 2).toString());
            txtCadFornecedorTelefone.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 3).toString());
            txtCadFornecedorEmail.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 4).toString());
            /*
            txtCadClienteCelular.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 4).toString());
            txtCadClienteEndereco.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 5).toString());
            txtCadClienteNome.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 1).toString());
            txtCadClienteNome.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 1).toString());
            txtCadClienteNome.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 1).toString());
            txtCadClienteNome.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 1).toString());
            txtCadClienteNome.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 1).toString());
            txtCadClienteNome.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 1).toString());
            */
            
        }
    }//GEN-LAST:event_jTPesquisaUsuarioMouseClicked

    private void btnPesquisarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarUsuariosActionPerformed
        // TODO add your handling code here:
        while (jTPesquisaUsuario.getRowCount() > 0) {
            DefaultTableModel dm = (DefaultTableModel) jTPesquisaUsuario.getModel();
            dm.getDataVector().removeAllElements();
        }
        DefaultTableModel modelo = (DefaultTableModel)jTPesquisaUsuario.getModel();

        readJtableForDesc(txtPesquisarUsuariolBuscar.getText());

        /*
        while(jTPesquisaUsuario.getRowCount() > 0) {
            readJtableForDesc(txtPesquisarUsuariolBuscar.getText());
            DefaultTableModel model = (DefaultTableModel) jTPesquisaUsuario.getModel();
            model.getDataVector().removeAllElements();
            UsuarioDAO udao = new UsuarioDAO();
            Usuario p = new Usuario();

            model.addRow(new Object[]{
                p.getIdusuario(),
                p.getLogin(),
                p.getSenha(),
                p.getIdfuncionario(),
                p.getIdpermissao()

            });

        }*/
    }//GEN-LAST:event_btnPesquisarUsuariosActionPerformed

    private void btnFornecedorEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorEditarActionPerformed
        // Restriçao de Botoes
        btnFornecedorSalvar.setEnabled(true);
        btnFornecedorEditar.setEnabled(false);
        btnFornecedorDelete.setEnabled(false);
        btnFornecedorCancelar.setEnabled(false);
        txtPesquisarUsuariolBuscar.setEnabled(true);
        
        
        if (jTPesquisaUsuario.getSelectedRow() != -1) {
            Fornecedor p = new Fornecedor();
            FornecedorDAO pdao = new FornecedorDAO();
            
        p.setNome(txtCadFornecedorNome.getText());
        p.setNomeFantasia(txtCadFornecedorNomeFantasia.getText());
        p.setCnpj(txtCadFornecedorCNPJ.getText());
        p.setInEstadual(txtCadFornecedorInscEstadual.getText());
        p.setTelefone(txtCadFornecedorTelefone.getText());
        p.setCelular(txtCadFornecedorCelular.getText());
        p.setEmail(txtCadFornecedorEmail.getText());
        //p.setDataCadastro(txtCadFornecedorDataCadastro.getText());
        p.setEndereco(txtCadFornecedorEndereco.getText());
        p.setBairro(txtCadFornecedorBairro.getText());
        p.setCidade(txtCadFornecedorCidade.getText());
        p.setCep(txtCadFornecedorCep.getText());
        p.setEstado((String)jbCadFornecedorEstado.getSelectedItem());
        p.setId((int)jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 0));
        
         try {
            pdao.update(p);
            JOptionPane.showMessageDialog(null, "Editado com sucesso!");
            //apagar campos ao Editar
            txtCadFornecedorNome.setText("");
            txtCadFornecedorNomeFantasia.setText("");
            txtCadFornecedorCNPJ.setText("");
            txtCadFornecedorInscEstadual.setText("");
            txtCadFornecedorTelefone.setText("");
            txtCadFornecedorCelular.setText("");
            txtCadFornecedorDataCadastro.setText("");
            txtCadFornecedorEndereco.setText("");
            txtCadFornecedorBairro.setText("");
            txtCadFornecedorCidade.setText("");
            txtCadFornecedorCep.setText("");
            jbCadFornecedorEstado.setSelectedItem("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao editar!" +ex);
            
        }   
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um Fornecedor na tabela de pesquisa!!");
        }
        
    }//GEN-LAST:event_btnFornecedorEditarActionPerformed

    private void btnFornecedorDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorDeleteActionPerformed
        // Restriçao de Botoes
        btnFornecedorSalvar.setEnabled(true);
        btnFornecedorEditar.setEnabled(false);
        btnFornecedorDelete.setEnabled(false);
        btnFornecedorCancelar.setEnabled(false);
        txtPesquisarUsuariolBuscar.setEnabled(true);

        if (jTPesquisaUsuario.getSelectedRow() != -1) {
            Fornecedor p = new Fornecedor();
            FornecedorDAO pdao = new FornecedorDAO();

            p.setId((int) jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 0));

            try {
                pdao.delete(p);
                txtCadFornecedorNome.setText("");
                txtCadFornecedorNomeFantasia.setText("");
                txtCadFornecedorCNPJ.setText("");
                txtCadFornecedorInscEstadual.setText("");
                txtCadFornecedorTelefone.setText("");
                txtCadFornecedorCelular.setText("");
                txtCadFornecedorDataCadastro.setText("");
                txtCadFornecedorEndereco.setText("");
                txtCadFornecedorBairro.setText("");
                txtCadFornecedorCidade.setText("");
                txtCadFornecedorCep.setText("");
                jbCadFornecedorEstado.setSelectedItem("");
                
            } catch (SQLException ex) {
                Logger.getLogger(EstoqueCadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else{
            JOptionPane.showMessageDialog(null, "Selecione um item da tabela de pesquisa!");
                    
        }
    }//GEN-LAST:event_btnFornecedorDeleteActionPerformed

    private void txtPesquisarUsuariolBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarUsuariolBuscarKeyTyped
        // TODO add your handling code here:
        int limite=40;
        if(txtPesquisarUsuariolBuscar.getText().length()==limite){
            evt.consume();
        }          
    }//GEN-LAST:event_txtPesquisarUsuariolBuscarKeyTyped

    private void txtCadFornecedorNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadFornecedorNomeKeyTyped
        // TODO add your handling code here:
        int limite=40;
        if(txtCadFornecedorNome.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtCadFornecedorNomeKeyTyped

    private void txtCadFornecedorNomeFantasiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadFornecedorNomeFantasiaKeyTyped
        // TODO add your handling code here:
        int limite=40;
        if(txtCadFornecedorNomeFantasia.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtCadFornecedorNomeFantasiaKeyTyped

    private void txtCadFornecedorEnderecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadFornecedorEnderecoKeyTyped
        // TODO add your handling code here:
        int limite=60;
        if(txtCadFornecedorEndereco.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtCadFornecedorEnderecoKeyTyped

    private void txtCadFornecedorBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadFornecedorBairroKeyTyped
        // TODO add your handling code here:
        int limite=20;
        if(txtCadFornecedorBairro.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtCadFornecedorBairroKeyTyped

    private void txtCadFornecedorCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadFornecedorCidadeKeyTyped
        // TODO add your handling code here:
        int limite=20;
        if(txtCadFornecedorCidade.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtCadFornecedorCidadeKeyTyped

    private void txtPesquisarUsuariolBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarUsuariolBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarUsuariolBuscarActionPerformed
       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFornecedorAjuda;
    private javax.swing.JButton btnFornecedorCancelar;
    private javax.swing.JButton btnFornecedorDelete;
    private javax.swing.JButton btnFornecedorEditar;
    private javax.swing.JButton btnFornecedorSalvar;
    private javax.swing.JButton btnPesquisarUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTPesquisaUsuario;
    private javax.swing.JComboBox jbCadFornecedorEstado;
    private javax.swing.JToolBar jtbFornecedorBarraFerramenta;
    private javax.swing.JLabel lbPesquisarUsuariolBuscar;
    private javax.swing.JLabel lblCadFornecedorBairro;
    private javax.swing.JLabel lblCadFornecedorCNPJ;
    private javax.swing.JLabel lblCadFornecedorCelular;
    private javax.swing.JLabel lblCadFornecedorCep;
    private javax.swing.JLabel lblCadFornecedorCidade;
    private javax.swing.JLabel lblCadFornecedorDataCadastro;
    private javax.swing.JLabel lblCadFornecedorEmail;
    private javax.swing.JLabel lblCadFornecedorEndereco;
    private javax.swing.JLabel lblCadFornecedorEstado;
    private javax.swing.JLabel lblCadFornecedorInscEstadual;
    private javax.swing.JLabel lblCadFornecedorNome;
    private javax.swing.JLabel lblCadFornecedorNomeFantasia;
    private javax.swing.JLabel lblCadFornecedorTelefone;
    private javax.swing.JTextField txtCadFornecedorBairro;
    private javax.swing.JFormattedTextField txtCadFornecedorCNPJ;
    private javax.swing.JFormattedTextField txtCadFornecedorCelular;
    private javax.swing.JFormattedTextField txtCadFornecedorCep;
    private javax.swing.JTextField txtCadFornecedorCidade;
    private javax.swing.JLabel txtCadFornecedorDataCadastro;
    private javax.swing.JFormattedTextField txtCadFornecedorEmail;
    private javax.swing.JTextField txtCadFornecedorEndereco;
    private javax.swing.JFormattedTextField txtCadFornecedorInscEstadual;
    private javax.swing.JTextField txtCadFornecedorNome;
    private javax.swing.JTextField txtCadFornecedorNomeFantasia;
    private javax.swing.JFormattedTextField txtCadFornecedorTelefone;
    private javax.swing.JTextField txtPesquisarUsuariolBuscar;
    // End of variables declaration//GEN-END:variables
}
