/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Conexao.ModuloConexao;
import DAO.UsuarioDAO;
import JavaBean.Usuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Walleson Moura
 */
public class CadastroUsuario extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int codfuncionario;

    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario() {
        initComponents();
        conexao = ModuloConexao.conector();
        carregafuncionario();
        //buscarfuncionario();
        
    }
   public void readJtableForDesc (String desc){
        DefaultTableModel modelo = (DefaultTableModel)jTPesquisaUsuario.getModel();
        UsuarioDAO udao = new UsuarioDAO();
        try {
            for (Usuario p: udao.readForDesc(desc)) {
                
                modelo.addRow(new Object[]{
                    p.getIdusuario(),
                    p.getLogin(),
                    p.getSenha(),
                    //p.getIdfuncionario(),
                    p.getPermissao()
                    
                });
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
   
     //Pega Nome Funcionario Jcomboxbox
    public void carregafuncionario() {
        //Lucas
        try {

            java.sql.Statement st=conexao.createStatement();
            ResultSet rs= st.executeQuery("select nome from funcionarios order by nome;");
            jbCadUsuarioFuncionario.removeAllItems();
            while(rs.next()){
                jbCadUsuarioFuncionario.addItem(rs.getString(1));
              
            }
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    // Buscar id Funcionario 
    public void buscarfuncionario(String nome) throws SQLException{
        // LUCAS
        String sql = "select * from funcionarios WHERE nome='"+nome+"'";
        try { pst = conexao.prepareStatement(sql);
              rs = pst.executeQuery();
              rs.next();
              codfuncionario=rs.getInt("id");
              
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
            

            
        
        
        /*String sql = "select * from funcionarios WHERE nome='"+nome+"'";
       // try {
            //java.sql.Statement st=conexao.createStatement();
            //ResultSet rs= st.executeQuery("select * from funcionarios WHERE nome='"+nome+"'");
           // txtCadUsuarioFuncionario.removeAllItems();
            
            
            
           //pst = conexao.prepareStatement(sql);
            //rs = pst.executeQuery();
            //codfuncionario=conexao.rs.getInt
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }*/
            
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbCadUsuarioBarraFerramenta = new javax.swing.JToolBar();
        btnCadUsuarioSalvar = new javax.swing.JButton();
        btnCadUsuarioEditar = new javax.swing.JButton();
        btnCadUsuarioDelete = new javax.swing.JButton();
        btnCadUsuarioCancelar = new javax.swing.JButton();
        btnCadUsuarioAjudar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPesquisaUsuario = new javax.swing.JTable();
        lbPesquisarUsuariolBuscar = new javax.swing.JLabel();
        txtPesquisarUsuariolBuscar = new javax.swing.JTextField();
        btnPesquisarUsuarios = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblCadUsuarioLogin = new javax.swing.JLabel();
        lblCadUsuarioSenha = new javax.swing.JLabel();
        lblCadUsuarioFuncionario = new javax.swing.JLabel();
        lblCadUsuarioPermissao = new javax.swing.JLabel();
        txtCadUsuarioLogin = new javax.swing.JTextField();
        txtCadUsuarioSenha = new javax.swing.JTextField();
        jcbCadUsuarioPermissao = new javax.swing.JComboBox<String>();
        jbCadUsuarioFuncionario = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuário");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jtbCadUsuarioBarraFerramenta.setFloatable(false);
        jtbCadUsuarioBarraFerramenta.setRollover(true);

        btnCadUsuarioSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/salvar.png"))); // NOI18N
        btnCadUsuarioSalvar.setText("Salvar");
        btnCadUsuarioSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadUsuarioSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadUsuarioSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuarioSalvarActionPerformed(evt);
            }
        });
        jtbCadUsuarioBarraFerramenta.add(btnCadUsuarioSalvar);

        btnCadUsuarioEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit.png"))); // NOI18N
        btnCadUsuarioEditar.setText("Editar");
        btnCadUsuarioEditar.setFocusable(false);
        btnCadUsuarioEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadUsuarioEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadUsuarioEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuarioEditarActionPerformed(evt);
            }
        });
        jtbCadUsuarioBarraFerramenta.add(btnCadUsuarioEditar);

        btnCadUsuarioDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btnCadUsuarioDelete.setText("Excluir");
        btnCadUsuarioDelete.setFocusable(false);
        btnCadUsuarioDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadUsuarioDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadUsuarioDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuarioDeleteActionPerformed(evt);
            }
        });
        jtbCadUsuarioBarraFerramenta.add(btnCadUsuarioDelete);

        btnCadUsuarioCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancelar.png"))); // NOI18N
        btnCadUsuarioCancelar.setText("Limpar");
        btnCadUsuarioCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadUsuarioCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadUsuarioCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuarioCancelarActionPerformed(evt);
            }
        });
        jtbCadUsuarioBarraFerramenta.add(btnCadUsuarioCancelar);

        btnCadUsuarioAjudar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Help.png"))); // NOI18N
        btnCadUsuarioAjudar.setText("Ajuda");
        btnCadUsuarioAjudar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadUsuarioAjudar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadUsuarioAjudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuarioAjudarActionPerformed(evt);
            }
        });
        jtbCadUsuarioBarraFerramenta.add(btnCadUsuarioAjudar);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));

        jTPesquisaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "LOGIN", "SENHA", "PERMISSÃO"
            }
        ));
        jTPesquisaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPesquisaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTPesquisaUsuario);
        if (jTPesquisaUsuario.getColumnModel().getColumnCount() > 0) {
            jTPesquisaUsuario.getColumnModel().getColumn(0).setResizable(false);
            jTPesquisaUsuario.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTPesquisaUsuario.getColumnModel().getColumn(3).setResizable(false);
            jTPesquisaUsuario.getColumnModel().getColumn(3).setPreferredWidth(40);
        }

        lbPesquisarUsuariolBuscar.setText("Buscar:");

        btnPesquisarUsuarios.setText("Pesquisar");
        btnPesquisarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbPesquisarUsuariolBuscar)
                        .addGap(15, 15, 15)
                        .addComponent(txtPesquisarUsuariolBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarUsuarios)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPesquisarUsuariolBuscar)
                    .addComponent(txtPesquisarUsuariolBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarUsuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCadUsuarioLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadUsuarioLogin.setText("Login");

        lblCadUsuarioSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadUsuarioSenha.setText("Senha");

        lblCadUsuarioFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadUsuarioFuncionario.setText("Funcionário");

        lblCadUsuarioPermissao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCadUsuarioPermissao.setText("Permissão");

        txtCadUsuarioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadUsuarioLoginActionPerformed(evt);
            }
        });
        txtCadUsuarioLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCadUsuarioLoginKeyTyped(evt);
            }
        });

        txtCadUsuarioSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCadUsuarioSenhaKeyTyped(evt);
            }
        });

        jcbCadUsuarioPermissao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "administrador", "usuario", "tecnico" }));

        jbCadUsuarioFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadUsuarioFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCadUsuarioFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCadUsuarioLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCadUsuarioSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCadUsuarioPermissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCadUsuarioSenha, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCadUsuarioLogin)
                    .addComponent(jcbCadUsuarioPermissao, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadUsuarioFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCadUsuarioLogin)
                    .addComponent(txtCadUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadUsuarioSenha)
                    .addComponent(txtCadUsuarioSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadUsuarioFuncionario)
                    .addComponent(jbCadUsuarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadUsuarioPermissao)
                    .addComponent(jcbCadUsuarioPermissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbCadUsuarioBarraFerramenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbCadUsuarioBarraFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadUsuarioSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuarioSalvarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        Usuario cadastrar = new Usuario();
        cadastrar.setLogin(txtCadUsuarioLogin.getText());
        cadastrar.setSenha(txtCadUsuarioSenha.getText());
        cadastrar.setPermissao(jcbCadUsuarioPermissao.getSelectedItem()+"");
        cadastrar.setIdfuncionario(codfuncionario);
        //cadastrar.setIdfuncionario(Integer.parseInt(jbCadUsuarioFuncionario.getText()));
        
        UsuarioDAO dao = new UsuarioDAO();
        
        try {
            dao.cadastrarUsuario(cadastrar);
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
            txtCadUsuarioLogin.setText("");
            txtCadUsuarioSenha.setText("");
            //txtCadUsuarioFuncionario.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar!" +ex);
            
        }

      

       
    }//GEN-LAST:event_btnCadUsuarioSalvarActionPerformed

    private void btnCadUsuarioEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuarioEditarActionPerformed
        // TODO add your handling code here:
        // Restriçao de Botoes
        btnCadUsuarioSalvar.setEnabled(true);
        btnCadUsuarioEditar.setEnabled(false);
        btnCadUsuarioDelete.setEnabled(false);
        btnCadUsuarioCancelar.setEnabled(false);
        
        if (jTPesquisaUsuario.getSelectedRow() != -1) {
            Usuario p = new Usuario();
            UsuarioDAO pdao = new UsuarioDAO();
            

            p.setLogin(txtCadUsuarioLogin.getText());
            p.setSenha(txtCadUsuarioSenha.getText());
            p.setIdfuncionario(codfuncionario);
            p.setPermissao(jcbCadUsuarioPermissao.getSelectedItem()+"");
            p.setIdusuario((int)jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 0));
            
          
            
            
            try {
                pdao.update(p);
                txtCadUsuarioLogin.setText("");
                txtCadUsuarioSenha.setText("");
                //txtCadUsuarioFuncionario.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(EstoqueCadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnCadUsuarioEditarActionPerformed
    }
    private void btnCadUsuarioCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuarioCancelarActionPerformed
       // TODO add your handling code here:
        // Restriçao de Botoes
        btnCadUsuarioSalvar.setEnabled(true);
        btnCadUsuarioEditar.setEnabled(false);
        btnCadUsuarioDelete.setEnabled(false);
        btnCadUsuarioCancelar.setEnabled(false);
        //zera os valores
        txtCadUsuarioLogin.setText("");
        txtCadUsuarioSenha.setText("");
        //txtCadUsuarioFuncionario.setText("");
       

    }//GEN-LAST:event_btnCadUsuarioCancelarActionPerformed

    private void txtCadUsuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadUsuarioLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadUsuarioLoginActionPerformed

    private void jTPesquisaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPesquisaUsuarioMouseClicked
        // TODO add your handling code here:
        // Restriçao de Botoes e Telas
        btnCadUsuarioSalvar.setEnabled(false);
        btnCadUsuarioEditar.setEnabled(true);
        btnCadUsuarioDelete.setEnabled(true);
        btnCadUsuarioCancelar.setEnabled(true);       
        
        CadastroUsuario pesquisa = new CadastroUsuario();
        if(jTPesquisaUsuario.getSelectedRow() != -1){

            txtCadUsuarioLogin.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 1).toString());
            txtCadUsuarioSenha.setText(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 2).toString());
            //txtCadUsuarioFuncionario.setText((String) jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 3));
            jcbCadUsuarioPermissao.setSelectedItem(jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 3).toString());

        }
    }//GEN-LAST:event_jTPesquisaUsuarioMouseClicked

    private void btnPesquisarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarUsuariosActionPerformed
        // TODO add your handling code here:
        while (jTPesquisaUsuario.getRowCount() > 0) {
            DefaultTableModel dm = (DefaultTableModel) jTPesquisaUsuario.getModel();
            dm.getDataVector().removeAllElements();
        }
        DefaultTableModel modelo = (DefaultTableModel)jTPesquisaUsuario.getModel();

        readJtableForDesc(txtPesquisarUsuariolBuscar.getText());

        /*
        while(jTPesquisaUsuario.getRowCount() > 0) {
            readJtableForDesc(txtPesquisarUsuariolBuscar.getText());
            DefaultTableModel model = (DefaultTableModel) jTPesquisaUsuario.getModel();
            model.getDataVector().removeAllElements();
            UsuarioDAO udao = new UsuarioDAO();
            Usuario p = new Usuario();

            model.addRow(new Object[]{
                p.getIdusuario(),
                p.getLogin(),
                p.getSenha(),
                p.getIdfuncionario(),
                p.getIdpermissao()

            });

        }*/

    }//GEN-LAST:event_btnPesquisarUsuariosActionPerformed

    private void btnCadUsuarioDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuarioDeleteActionPerformed
        // TODO add your handling code here:
        // Restriçao de Botoes
        btnCadUsuarioSalvar.setEnabled(true);
        btnCadUsuarioEditar.setEnabled(false);
        btnCadUsuarioDelete.setEnabled(false);
        btnCadUsuarioCancelar.setEnabled(false);
        
         if (jTPesquisaUsuario.getSelectedRow() != -1) {
            Usuario p = new Usuario();
            UsuarioDAO pdao = new UsuarioDAO();

            p.setIdusuario((int) jTPesquisaUsuario.getValueAt(jTPesquisaUsuario.getSelectedRow(), 0));

             try {
                 pdao.delete(p);
                 txtCadUsuarioLogin.setText("");
                 txtCadUsuarioSenha.setText("");
                 //txtCadUsuarioFuncionario.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(EstoqueCadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
            }

            //JOptionPane.showMessageDialog(null, "Editado com sucesso!");
        }
    }//GEN-LAST:event_btnCadUsuarioDeleteActionPerformed

    private void txtCadUsuarioLoginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadUsuarioLoginKeyTyped
        // TODO add your handling code here:
         int limite=10;
        if(txtCadUsuarioLogin.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtCadUsuarioLoginKeyTyped

    private void txtCadUsuarioSenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadUsuarioSenhaKeyTyped
        // TODO add your handling code here:
        int limite=10;
        if(txtCadUsuarioSenha.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtCadUsuarioSenhaKeyTyped

    private void jbCadUsuarioFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadUsuarioFuncionarioActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
    }//GEN-LAST:event_jbCadUsuarioFuncionarioActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        // Abre tela com Botoes desativados
        btnCadUsuarioEditar.setEnabled(false);
        btnCadUsuarioDelete.setEnabled(false);
        btnCadUsuarioCancelar.setEnabled(false); 
    }//GEN-LAST:event_formWindowActivated

    private void btnCadUsuarioAjudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuarioAjudarActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,"                                                                            OS GESTOR \n"
                                             + "Olá, precisa de ajuda?\n"
                                             +"\n"
                                             + "*Deseja salvar? Para isso primeiro preencha os campos abaixo em seguida salve o cadastro. \n"
                                             + "\n"
                                             + "*Deseja editar? Para isso é necessario que primeiro efetue a pesquisa,\n "
                                             + "selecione o funcionario para alteração e em seguinda faça a alteração de acordo com a necessidade.\n"
                                             + "\n"
                                             + "*Deseja excluir? Para excluir efetue a pesquisa pelo funcionario que deseja excluir, "
                                             
                                              + "selecione e exclua.\n "
                                             +"\n"
                                             +"*Deseja pesquisar? Para pesquisar digite no campo de pesquisa os dados desejados.\n"
                                             +"\n"
                                             +" *Digitou errado? basta acionar o botão limpar para limpar todos os campos.\n"
                                             +"\n");
    }//GEN-LAST:event_btnCadUsuarioAjudarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadUsuarioAjudar;
    private javax.swing.JButton btnCadUsuarioCancelar;
    private javax.swing.JButton btnCadUsuarioDelete;
    private javax.swing.JButton btnCadUsuarioEditar;
    private javax.swing.JButton btnCadUsuarioSalvar;
    private javax.swing.JButton btnPesquisarUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTPesquisaUsuario;
    private javax.swing.JComboBox jbCadUsuarioFuncionario;
    private javax.swing.JComboBox<String> jcbCadUsuarioPermissao;
    private javax.swing.JToolBar jtbCadUsuarioBarraFerramenta;
    private javax.swing.JLabel lbPesquisarUsuariolBuscar;
    private javax.swing.JLabel lblCadUsuarioFuncionario;
    private javax.swing.JLabel lblCadUsuarioLogin;
    private javax.swing.JLabel lblCadUsuarioPermissao;
    private javax.swing.JLabel lblCadUsuarioSenha;
    private javax.swing.JTextField txtCadUsuarioLogin;
    private javax.swing.JTextField txtCadUsuarioSenha;
    private javax.swing.JTextField txtPesquisarUsuariolBuscar;
    // End of variables declaration//GEN-END:variables

    
}
