/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.sql.*;
import Conexao.ModuloConexao;
import DAO.ProdutosDAO;
import JavaBean.Produto;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author wramu
 */
public class EstoqueCadastrarProduto extends javax.swing.JFrame {
    static Connection conexao;
    
    

    /**
     * Creates new form EstoqueCadastrarProduto
     */
    public EstoqueCadastrarProduto() {
        initComponents();
        readJtable();
    }
    
    //ler e implantar linhas a tabelar, ataulizando ao salvar
 public void readJtable (){
        DefaultTableModel modelo = (DefaultTableModel)jTControleProdutos.getModel();
        ProdutosDAO pdao = new ProdutosDAO();
        try {
            for (Produto p: pdao.read()) {
                
                modelo.addRow(new Object[]{
                    p.getIdproduto(),
                    p.getDescricao(),
                    p.getPrecoCompra(),
                    p.getPrecoVenda(),
                    p.getFornecedor(),
                    p.getQuantidade()
                });
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEstoqueCadPro_nome = new javax.swing.JLabel();
        txtEstoqueCadPro_nome = new javax.swing.JTextField();
        lblEstoqueCadPro_preCompra = new javax.swing.JLabel();
        lblEstoqueCadPro_preVenda = new javax.swing.JLabel();
        lblEstoqueCadPro_fornecedor = new javax.swing.JLabel();
        txtEstoqueCadPro_fornecedor = new javax.swing.JTextField();
        jtbCadProBarraFerramenta = new javax.swing.JToolBar();
        btnCadProSalvar = new javax.swing.JToggleButton();
        btnCadProEditar = new javax.swing.JButton();
        btnCadProDelete = new javax.swing.JButton();
        btnCadProCancelar = new javax.swing.JButton();
        btnCadProAjuda = new javax.swing.JButton();
        lblCadPro_quantidade = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTControleProdutos = new javax.swing.JTable();
        txtEstoqueCadPro_preCompra = new javax.swing.JFormattedTextField();
        txtEstoqueCadPro_preVenda = new javax.swing.JFormattedTextField();
        txtCadPro_quantidade = new javax.swing.JFormattedTextField();
        jbAdicinonar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Produto");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblEstoqueCadPro_nome.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEstoqueCadPro_nome.setText("*Nome:");

        txtEstoqueCadPro_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstoqueCadPro_nomeActionPerformed(evt);
            }
        });
        txtEstoqueCadPro_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstoqueCadPro_nomeKeyTyped(evt);
            }
        });

        lblEstoqueCadPro_preCompra.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEstoqueCadPro_preCompra.setText("*Preço de Compra:");

        lblEstoqueCadPro_preVenda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstoqueCadPro_preVenda.setText("*Preço de Venda:");

        lblEstoqueCadPro_fornecedor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEstoqueCadPro_fornecedor.setText("Fornecedor:");

        txtEstoqueCadPro_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstoqueCadPro_fornecedorActionPerformed(evt);
            }
        });

        jtbCadProBarraFerramenta.setFloatable(false);
        jtbCadProBarraFerramenta.setRollover(true);

        btnCadProSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/salvar.png"))); // NOI18N
        btnCadProSalvar.setSelected(true);
        btnCadProSalvar.setText("Salvar");
        btnCadProSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadProSalvar.setName(""); // NOI18N
        btnCadProSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadProSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadProSalvarActionPerformed(evt);
            }
        });
        jtbCadProBarraFerramenta.add(btnCadProSalvar);

        btnCadProEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit.png"))); // NOI18N
        btnCadProEditar.setText("Editar");
        btnCadProEditar.setFocusable(false);
        btnCadProEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadProEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadProEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadProEditarActionPerformed(evt);
            }
        });
        jtbCadProBarraFerramenta.add(btnCadProEditar);

        btnCadProDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btnCadProDelete.setText("Excluir");
        btnCadProDelete.setFocusable(false);
        btnCadProDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadProDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadProDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadProDeleteActionPerformed(evt);
            }
        });
        jtbCadProBarraFerramenta.add(btnCadProDelete);

        btnCadProCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancelar.png"))); // NOI18N
        btnCadProCancelar.setText("Limpar");
        btnCadProCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadProCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadProCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadProCancelarActionPerformed(evt);
            }
        });
        jtbCadProBarraFerramenta.add(btnCadProCancelar);

        btnCadProAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Help.png"))); // NOI18N
        btnCadProAjuda.setText("Ajuda");
        btnCadProAjuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadProAjuda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadProAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadProAjudaActionPerformed(evt);
            }
        });
        jtbCadProBarraFerramenta.add(btnCadProAjuda);

        lblCadPro_quantidade.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCadPro_quantidade.setText("*Quantidade:");

        jTControleProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "PREÇO COMPRA", "PREÇO VENDA", "FORNECEDOR", "QUANTIDADE"
            }
        ));
        jTControleProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTControleProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTControleProdutos);
        if (jTControleProdutos.getColumnModel().getColumnCount() > 0) {
            jTControleProdutos.getColumnModel().getColumn(0).setPreferredWidth(40);
        }

        txtEstoqueCadPro_preCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstoqueCadPro_preCompraActionPerformed(evt);
            }
        });

        txtEstoqueCadPro_preVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstoqueCadPro_preVendaActionPerformed(evt);
            }
        });

        txtCadPro_quantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtCadPro_quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadPro_quantidadeActionPerformed(evt);
            }
        });

        jbAdicinonar.setText("Adicionar");
        jbAdicinonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicinonarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbCadProBarraFerramenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEstoqueCadPro_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblCadPro_quantidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEstoqueCadPro_fornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEstoqueCadPro_preCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCadPro_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEstoqueCadPro_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbAdicinonar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEstoqueCadPro_preCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(209, 209, 209)
                                .addComponent(lblEstoqueCadPro_preVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstoqueCadPro_preVenda))
                            .addComponent(txtEstoqueCadPro_nome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jtbCadProBarraFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstoqueCadPro_nome)
                    .addComponent(txtEstoqueCadPro_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstoqueCadPro_preCompra)
                    .addComponent(lblEstoqueCadPro_preVenda)
                    .addComponent(txtEstoqueCadPro_preCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstoqueCadPro_preVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstoqueCadPro_fornecedor)
                    .addComponent(txtEstoqueCadPro_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAdicinonar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadPro_quantidade)
                    .addComponent(txtCadPro_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadProSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadProSalvarActionPerformed
        // TODO add your handling code here:
       
        Produto cadastrar = new Produto();

        cadastrar.setDescricao(txtEstoqueCadPro_nome.getText());
        cadastrar.setPrecoCompra(Float.parseFloat(txtEstoqueCadPro_preCompra.getText()));
        cadastrar.setPrecoVenda(Float.parseFloat(txtEstoqueCadPro_preVenda.getText()));
        cadastrar.setFornecedor(txtEstoqueCadPro_fornecedor.getText());
        cadastrar.setQuantidade(Integer.parseInt(txtCadPro_quantidade.getText()));

        ProdutosDAO dao = new ProdutosDAO();

        try {
            dao.cadastrarProduto(cadastrar);
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
            txtEstoqueCadPro_nome.setText("");
            txtEstoqueCadPro_preCompra.setText("");
            txtEstoqueCadPro_preVenda.setText("");
            txtEstoqueCadPro_fornecedor.setText("");
            txtCadPro_quantidade.setText("");

            //limpar e atualizar tabela
            while (jTControleProdutos.getRowCount() > 0) {
                DefaultTableModel dm = (DefaultTableModel) jTControleProdutos.getModel();
                dm.getDataVector().removeAllElements();
            }
            DefaultTableModel modelo = (DefaultTableModel) jTControleProdutos.getModel();

            ProdutosDAO pdao = new ProdutosDAO();
            try {
                
                for (Produto p : pdao.read()) {

                    modelo.addRow(new Object[]{
                        p.getIdproduto(),
                        p.getDescricao(),
                        p.getPrecoCompra(),
                        p.getPrecoVenda(),
                        p.getFornecedor(),
                        p.getQuantidade()
                    });

                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar!" + ex);

        }


    }//GEN-LAST:event_btnCadProSalvarActionPerformed

    private void btnCadProCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadProCancelarActionPerformed
        // TODO add your handling code here:
        // Restriçao de Botoes
        btnCadProSalvar.setEnabled(true);
        btnCadProEditar.setEnabled(false);
        btnCadProDelete.setEnabled(false);
        btnCadProCancelar.setEnabled(false);
        // Lipar Campos
        txtEstoqueCadPro_nome.setText("");
        txtEstoqueCadPro_preCompra.setText("");
        txtEstoqueCadPro_preVenda.setText("");
        txtEstoqueCadPro_fornecedor.setText("");
        txtCadPro_quantidade.setText("");
        

    }//GEN-LAST:event_btnCadProCancelarActionPerformed

    private void txtEstoqueCadPro_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstoqueCadPro_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstoqueCadPro_nomeActionPerformed

    private void btnCadProEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadProEditarActionPerformed
        // TODO add your handling code here:
        // Restriçao de Botoes
        btnCadProSalvar.setEnabled(true);
        btnCadProEditar.setEnabled(false);
        btnCadProDelete.setEnabled(false);
        btnCadProCancelar.setEnabled(false);
            
       
        if (jTControleProdutos.getSelectedRow() != -1) {
            Produto p = new Produto();
            ProdutosDAO pdao = new ProdutosDAO();
            

            p.setDescricao(txtEstoqueCadPro_nome.getText());
            p.setPrecoCompra(Float.parseFloat(txtEstoqueCadPro_preCompra.getText()));
            p.setPrecoVenda(Float.parseFloat(txtEstoqueCadPro_preVenda.getText()));
            p.setFornecedor(txtEstoqueCadPro_fornecedor.getText());
            p.setQuantidade(Integer.parseInt(txtCadPro_quantidade.getText()));
            p.setIdproduto((int)jTControleProdutos.getValueAt(jTControleProdutos.getSelectedRow(), 0));
            try {
                pdao.update(p);
            } catch (SQLException ex) {
                Logger.getLogger(EstoqueCadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            //JOptionPane.showMessageDialog(null, "Editado com sucesso!");
             
        } 
        //limpar e atualizar tabela
         while (jTControleProdutos.getRowCount() > 0) {
                DefaultTableModel dm = (DefaultTableModel) jTControleProdutos.getModel();
                dm.getDataVector().removeAllElements();
            }
            DefaultTableModel modelo = (DefaultTableModel) jTControleProdutos.getModel();

            ProdutosDAO pdao = new ProdutosDAO();
            try {
                
                for (Produto p : pdao.read()) {

                    modelo.addRow(new Object[]{
                        p.getIdproduto(),
                        p.getDescricao(),
                        p.getPrecoCompra(),
                        p.getPrecoVenda(),
                        p.getFornecedor(),
                        p.getQuantidade()
                    });

                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        

    }//GEN-LAST:event_btnCadProEditarActionPerformed

    private void jTControleProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTControleProdutosMouseClicked
        // TODO add your handling code here:
        // Restriçao de Botoes e Telas
        btnCadProSalvar.setEnabled(false);
        btnCadProEditar.setEnabled(true);
        btnCadProDelete.setEnabled(true);
        btnCadProCancelar.setEnabled(true);
        
        if(jTControleProdutos.getSelectedRow() != -1){
            
           txtEstoqueCadPro_nome.setText(jTControleProdutos.getValueAt(jTControleProdutos.getSelectedRow(), 1).toString()); 
           txtEstoqueCadPro_preCompra.setText(jTControleProdutos.getValueAt(jTControleProdutos.getSelectedRow(), 2).toString()); 
           txtEstoqueCadPro_preVenda.setText(jTControleProdutos.getValueAt(jTControleProdutos.getSelectedRow(), 3).toString()); 
           txtEstoqueCadPro_fornecedor.setText(jTControleProdutos.getValueAt(jTControleProdutos.getSelectedRow(), 4).toString()); 
           txtCadPro_quantidade.setText(jTControleProdutos.getValueAt(jTControleProdutos.getSelectedRow(), 5).toString()); 
           
        }
        
    }//GEN-LAST:event_jTControleProdutosMouseClicked

    private void btnCadProDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadProDeleteActionPerformed
        // TODO add your handling code here:
        // Restriçao de Botoes
        btnCadProSalvar.setEnabled(true);
        btnCadProEditar.setEnabled(false);
        btnCadProDelete.setEnabled(false);
        btnCadProCancelar.setEnabled(false);
             
       
        if (jTControleProdutos.getSelectedRow() != -1) {
            Produto p = new Produto();
            ProdutosDAO pdao = new ProdutosDAO();

            p.setIdproduto((int) jTControleProdutos.getValueAt(jTControleProdutos.getSelectedRow(), 0));

            try {
                pdao.delete(p);
            } catch (SQLException ex) {
                Logger.getLogger(EstoqueCadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
            }

            //JOptionPane.showMessageDialog(null, "Excluido com sucesso!");
        }
        //limpar e atualizar tabela
        while (jTControleProdutos.getRowCount() > 0) {
            DefaultTableModel dm = (DefaultTableModel) jTControleProdutos.getModel();
            dm.getDataVector().removeAllElements();
        }
        DefaultTableModel modelo = (DefaultTableModel) jTControleProdutos.getModel();

        ProdutosDAO pdao = new ProdutosDAO();
        try {

            for (Produto p : pdao.read()) {

                modelo.addRow(new Object[]{
                    p.getIdproduto(),
                    p.getDescricao(),
                    p.getPrecoCompra(),
                    p.getPrecoVenda(),
                    p.getFornecedor(),
                    p.getQuantidade()
                });

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }


    }//GEN-LAST:event_btnCadProDeleteActionPerformed

    private void txtEstoqueCadPro_preCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstoqueCadPro_preCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstoqueCadPro_preCompraActionPerformed

    private void txtEstoqueCadPro_preVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstoqueCadPro_preVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstoqueCadPro_preVendaActionPerformed

    private void txtCadPro_quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadPro_quantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadPro_quantidadeActionPerformed

    private void jbAdicinonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicinonarActionPerformed
        // TODO add your handling code here:
         CadastroFornecedor frm = new CadastroFornecedor();
         frm.setVisible(true);
                 
    }//GEN-LAST:event_jbAdicinonarActionPerformed

    private void txtEstoqueCadPro_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstoqueCadPro_fornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstoqueCadPro_fornecedorActionPerformed

    private void txtEstoqueCadPro_nomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstoqueCadPro_nomeKeyTyped
         // Limitando Caracteres
        int limite=40;
        if(txtEstoqueCadPro_nome.getText().length()==limite){
            evt.consume();
        }    
        
    }//GEN-LAST:event_txtEstoqueCadPro_nomeKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        // Abre tela com Botoes desativados
        btnCadProEditar.setEnabled(false);
        btnCadProDelete.setEnabled(false);
        btnCadProCancelar.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void btnCadProAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadProAjudaActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null,"                                                                            OS GESTOR \n"
                                             + "Olá, precisa de ajuda?\n"
                                             +"\n"
                                             + "*Deseja salvar? Para isso primeiro preencha os campos abaixo em seguida salve o cadastro. \n"
                                             + "\n"
                                             + "*Deseja editar? Para isso é necessario que primeiro efetue a pesquisa,\n "
                                             + "selecione o funcionario para alteração e em seguinda faça a alteração de acordo com a necessidade.\n"
                                             + "\n"
                                             + "*Deseja excluir? Para excluir efetue a pesquisa pelo funcionario que deseja excluir, "
                                             
                                              + "selecione e exclua.\n "
                                             +"\n"
                                             +"*Deseja pesquisar? Para pesquisar digite no campo de pesquisa os dados desejados.\n"
                                             +"\n"
                                             +" *Digitou errado? basta acionar o botão limpar para limpar todos os campos.\n"
                                             +"\n");
        
    }//GEN-LAST:event_btnCadProAjudaActionPerformed
    public void carregacombo (){
        ProdutosDAO mostrarFornecdorDAO=new ProdutosDAO();
        
       
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstoqueCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstoqueCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstoqueCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstoqueCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstoqueCadastrarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadProAjuda;
    private javax.swing.JButton btnCadProCancelar;
    private javax.swing.JButton btnCadProDelete;
    private javax.swing.JButton btnCadProEditar;
    private javax.swing.JToggleButton btnCadProSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTControleProdutos;
    private javax.swing.JButton jbAdicinonar;
    private javax.swing.JToolBar jtbCadProBarraFerramenta;
    private javax.swing.JLabel lblCadPro_quantidade;
    private javax.swing.JLabel lblEstoqueCadPro_fornecedor;
    private javax.swing.JLabel lblEstoqueCadPro_nome;
    private javax.swing.JLabel lblEstoqueCadPro_preCompra;
    private javax.swing.JLabel lblEstoqueCadPro_preVenda;
    private javax.swing.JFormattedTextField txtCadPro_quantidade;
    private javax.swing.JTextField txtEstoqueCadPro_fornecedor;
    private javax.swing.JTextField txtEstoqueCadPro_nome;
    private javax.swing.JFormattedTextField txtEstoqueCadPro_preCompra;
    private javax.swing.JFormattedTextField txtEstoqueCadPro_preVenda;
    // End of variables declaration//GEN-END:variables
}
