/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.*;
import Conexao.ModuloConexao;
import java.sql.ResultSet;
import DAO.ClientesDAO;
import net.proteanit.sql.DbUtils;
import DAO.OsDAO;
import JavaBean.Clientes;
import JavaBean.Os;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import JavaBean.Os;
import java.awt.HeadlessException;
import java.text.DateFormat;
import jxl.common.Logger;

/**
 *
 * @author Walleson Moura
 */
public class TeladeOS extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form TeladeOS
     */
    public TeladeOS() {
        initComponents();
        conexao = ModuloConexao.conector();

    }

    private void pesquisarCliente() {
        String sql = "select id as ID, nome as NOME, Telefone as TELEFONE from clientes WHERE nome LIKE ?";
        try {

            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtTelaOSPesquisaIdCli.getText() + "%");
            rs = pst.executeQuery();
            jTTelaOSPesquisaInfoCli.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void setarCampos() {
        int setar = jTTelaOSPesquisaInfoCli.getSelectedRow();
        txtTelaOSPesquisaIdCli.setText(jTTelaOSPesquisaInfoCli.getModel().getValueAt(setar, 0).toString());
    }
    public String tipo;
    
    // Metodo Pesquisa Oredem de serviço
    private void pequisarOs(){

        
        String NumOs = JOptionPane.showInputDialog("Numero da Ordem de Serviço");
        String sql = "select * from ordemservicos where id = "+NumOs;
        try{
                           // Restriçao de Botoes e Telas
              btnSalvar.setEnabled(false);
              btnEditar.setEnabled(true);
              btnDelete.setEnabled(true);
              btnCancelar.setEnabled(true);
              //txtTelaOsPesquisaNomeCliente.setEnabled(false);
              //jTTelaOSPesquisaInfoCli.setVisible(false);
              
            pst=conexao.prepareStatement(sql);
            rs=pst.executeQuery();
            if (rs.next()) {
                txtTelaOSNumOS.setText(rs.getString(1));
                txtTelaOsData.setText(rs.getString(2));
                jcbTelaOsGarantia.setSelectedItem(rs.getString(3));
                jtxDescOS.setText(rs.getString(4));
                txtTelaOsDefeito.setText(rs.getString(5));
                jcbTelaOsStatus.setSelectedItem(rs.getString(6));
                txtTelaOsServico.setText(rs.getString(7));
                txtValorOS.setText(rs.getString(8));
                txtTelaOSPesquisaIdCli.setText(rs.getString(9));
                txtTelaOsTec.setText(rs.getString(10));
                txtBuscarProdutId.setText(rs.getString(11));
                txtDescricao.setText(rs.getString(12));
                txtNserie.setText(rs.getString(13));
                txtModelo.setText(rs.getString(14));
                txtFabricante.setText(rs.getString(15));
                                       
                // Setar Buton
                String btTipo=rs.getString(16);
                if (btTipo.equals("Ordem de Servico")){
                    jrbTelaOSOS.setSelected(true);
                    tipo="Ordem de Servico";
                    
                }else {
                    jrbTelaOsOracamento.setSelected(true);
                    tipo="Orcamento";
                }
        
                               
            } else {
 
                JOptionPane.showMessageDialog(null, "Ordem de Serviço não Cadastrada");
            }
            
        }catch (com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException e) {
            JOptionPane.showMessageDialog(null,"Ordem de Serviço Inválida");
            //System.out.println(e); 
        }catch (Exception e2){
            JOptionPane.showMessageDialog(null,e2);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPclassOs = new javax.swing.JPanel();
        lblTelaOSNumOS = new javax.swing.JLabel();
        lblTelaOsData = new javax.swing.JLabel();
        txtTelaOSNumOS = new javax.swing.JTextField();
        jrbTelaOsOracamento = new javax.swing.JRadioButton();
        jrbTelaOSOS = new javax.swing.JRadioButton();
        txtTelaOsData = new javax.swing.JLabel();
        lblTelaOSStatus = new javax.swing.JLabel();
        jcbTelaOsStatus = new javax.swing.JComboBox<String>();
        jPPesquisa = new javax.swing.JPanel();
        txtTelaOsPesquisaNomeCliente = new javax.swing.JTextField();
        lblTelaOSPesquisaIdCli = new javax.swing.JLabel();
        txtTelaOSPesquisaIdCli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTelaOSPesquisaInfoCli = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblTelaOsDefeito = new javax.swing.JLabel();
        lblTelaOsServico = new javax.swing.JLabel();
        lblTelaOsTecnico = new javax.swing.JLabel();
        txtTelaOsDefeito = new javax.swing.JTextField();
        txtTelaOsServico = new javax.swing.JTextField();
        txtTelaOsTec = new javax.swing.JTextField();
        jtbBarraFerramenta = new javax.swing.JToolBar();
        btnSalvar = new javax.swing.JToggleButton();
        btnEditar = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAjuda = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        lblTelaOsDesc = new javax.swing.JLabel();
        lblTelaOsGarantia = new javax.swing.JLabel();
        jcbTelaOsGarantia = new javax.swing.JComboBox<String>();
        lblValor = new javax.swing.JLabel();
        pnlEquipamento = new javax.swing.JPanel();
        lblDescricao = new javax.swing.JLabel();
        lblNserie = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblFabricante = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtNserie = new javax.swing.JTextField();
        txtFabricante = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarProdutId = new javax.swing.JTextField();
        btnAddProduto = new javax.swing.JButton();
        txtValorOS = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxDescOS = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ordens de Serviço");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPclassOs.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTelaOSNumOS.setText("Nº OS:");

        lblTelaOsData.setText("Data:");

        txtTelaOSNumOS.setEditable(false);
        txtTelaOSNumOS.setEnabled(false);
        txtTelaOSNumOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelaOSNumOSActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbTelaOsOracamento);
        jrbTelaOsOracamento.setText("Orçamento");
        jrbTelaOsOracamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTelaOsOracamentoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbTelaOSOS);
        jrbTelaOSOS.setText("Ordem de Serviço");
        jrbTelaOSOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTelaOSOSActionPerformed(evt);
            }
        });

        txtTelaOsData.setText(" ");

        javax.swing.GroupLayout jPclassOsLayout = new javax.swing.GroupLayout(jPclassOs);
        jPclassOs.setLayout(jPclassOsLayout);
        jPclassOsLayout.setHorizontalGroup(
            jPclassOsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPclassOsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPclassOsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelaOSNumOS)
                    .addComponent(txtTelaOSNumOS, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbTelaOsOracamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPclassOsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelaOsData)
                    .addComponent(jrbTelaOSOS)
                    .addComponent(txtTelaOsData, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPclassOsLayout.setVerticalGroup(
            jPclassOsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPclassOsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPclassOsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelaOSNumOS)
                    .addComponent(lblTelaOsData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPclassOsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelaOSNumOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelaOsData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPclassOsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbTelaOsOracamento)
                    .addComponent(jrbTelaOSOS))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lblTelaOSStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelaOSStatus.setText("Status:");

        jcbTelaOsStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aguardando Aprovação", "Orçamento Reprovado", "Na Bancada", "Entrega Realizada", "Abandonado pelo Cliente", "Retornou" }));
        jcbTelaOsStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTelaOsStatusActionPerformed(evt);
            }
        });

        jPPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar Cliente"));

        txtTelaOsPesquisaNomeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelaOsPesquisaNomeClienteKeyReleased(evt);
            }
        });

        lblTelaOSPesquisaIdCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelaOSPesquisaIdCli.setText("*id:");

        txtTelaOSPesquisaIdCli.setEnabled(false);

        jTTelaOSPesquisaInfoCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "TELEFONE"
            }
        ));
        jTTelaOSPesquisaInfoCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTTelaOSPesquisaInfoCliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTTelaOSPesquisaInfoCli);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/jobs.png"))); // NOI18N

        javax.swing.GroupLayout jPPesquisaLayout = new javax.swing.GroupLayout(jPPesquisa);
        jPPesquisa.setLayout(jPPesquisaLayout);
        jPPesquisaLayout.setHorizontalGroup(
            jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPesquisaLayout.createSequentialGroup()
                        .addComponent(txtTelaOsPesquisaNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addComponent(lblTelaOSPesquisaIdCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelaOSPesquisaIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPPesquisaLayout.setVerticalGroup(
            jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPesquisaLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTelaOSPesquisaIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTelaOSPesquisaIdCli)
                        .addComponent(jLabel1))
                    .addComponent(txtTelaOsPesquisaNomeCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblTelaOsDefeito.setText("* Defeito:");

        lblTelaOsServico.setText("* Serviço:");

        lblTelaOsTecnico.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelaOsTecnico.setText("*Funcionário:");

        txtTelaOsDefeito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelaOsDefeitoKeyTyped(evt);
            }
        });

        txtTelaOsServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelaOsServicoActionPerformed(evt);
            }
        });
        txtTelaOsServico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelaOsServicoKeyTyped(evt);
            }
        });

        txtTelaOsTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelaOsTecActionPerformed(evt);
            }
        });
        txtTelaOsTec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelaOsTecKeyTyped(evt);
            }
        });

        jtbBarraFerramenta.setFloatable(false);
        jtbBarraFerramenta.setRollover(true);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/salvar.png"))); // NOI18N
        btnSalvar.setSelected(true);
        btnSalvar.setText("Salvar");
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setName(""); // NOI18N
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jtbBarraFerramenta.add(btnSalvar);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jtbBarraFerramenta.add(btnEditar);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btnDelete.setText("Excluir");
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jtbBarraFerramenta.add(btnDelete);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancelar.png"))); // NOI18N
        btnCancelar.setText("Limpar");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jtbBarraFerramenta.add(btnCancelar);

        btnAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Help.png"))); // NOI18N
        btnAjuda.setText("Ajuda");
        btnAjuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAjuda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudaActionPerformed(evt);
            }
        });
        jtbBarraFerramenta.add(btnAjuda);

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/jobs.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setFocusable(false);
        btnPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        jtbBarraFerramenta.add(btnPesquisar);

        lblTelaOsDesc.setText("Descrição:");

        lblTelaOsGarantia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelaOsGarantia.setText("Garantia:");

        jcbTelaOsGarantia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "15 Dias", "30 Dias", "60 Dias", "90 Dias" }));

        lblValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValor.setText("*Valor Total:");

        pnlEquipamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipamento"));

        lblDescricao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDescricao.setText("Descrição:");

        lblNserie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNserie.setText("Nº Série:");

        lblModelo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModelo.setText("Modelo:");

        lblFabricante.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFabricante.setText("Fabricante:");

        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyTyped(evt);
            }
        });

        txtNserie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNserieKeyTyped(evt);
            }
        });

        txtFabricante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFabricanteKeyTyped(evt);
            }
        });

        txtModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModeloKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlEquipamentoLayout = new javax.swing.GroupLayout(pnlEquipamento);
        pnlEquipamento.setLayout(pnlEquipamentoLayout);
        pnlEquipamentoLayout.setHorizontalGroup(
            pnlEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(lblNserie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txtNserie))
                .addGap(36, 36, 36)
                .addGroup(pnlEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFabricante, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txtFabricante))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEquipamentoLayout.setVerticalGroup(
            pnlEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(lblModelo)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnlEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNserie)
                    .addComponent(lblFabricante)
                    .addComponent(txtNserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("*Produto:");

        txtBuscarProdutId.setEnabled(false);

        btnAddProduto.setText("ADD");
        btnAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdutoActionPerformed(evt);
            }
        });

        txtValorOS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtValorOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorOSActionPerformed(evt);
            }
        });

        jtxDescOS.setColumns(20);
        jtxDescOS.setRows(5);
        jScrollPane2.setViewportView(jtxDescOS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbBarraFerramenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPclassOs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTelaOSStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbTelaOsStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlEquipamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTelaOsServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTelaOsDefeito))
                    .addComponent(lblTelaOsDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelaOsServico, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelaOsGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTelaOsTecnico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTelaOsTec, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBuscarProdutId)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbTelaOsGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtValorOS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTelaOsDefeito, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jtbBarraFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPclassOs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelaOSStatus)
                            .addComponent(jcbTelaOsStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelaOsDefeito)
                    .addComponent(txtTelaOsDefeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelaOsServico)
                    .addComponent(txtTelaOsServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelaOsTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelaOsTecnico))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelaOsDesc)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarProdutId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddProduto)
                            .addComponent(jLabel2))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValor)
                            .addComponent(txtValorOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbTelaOsGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelaOsGarantia)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelaOSNumOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelaOSNumOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelaOSNumOSActionPerformed

    private void txtTelaOsServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelaOsServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelaOsServicoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        Os emitir = new Os();
        
        //Validaçao de Campos Nulos
    if ((txtTelaOSPesquisaIdCli.getText().isEmpty()) || (txtTelaOsTec.getText().isEmpty()) || (txtBuscarProdutId.getText().isEmpty()) || (txtTelaOsDefeito.getText().isEmpty()) || (txtTelaOsServico.getText().isEmpty()) || (txtValorOS.getText().isEmpty()) ) {
            JOptionPane.showMessageDialog(null, "Preencha os Campos Obrigatórios");
    }else{
        
        emitir.setTipoOs(tipo);
        emitir.setStatus((String)jcbTelaOsStatus.getSelectedItem());
        emitir.setIdCliente(Integer.parseInt(txtTelaOSPesquisaIdCli.getText()));
        emitir.setEqpDesc(txtDescricao.getText());
        emitir.setEqpFabric(txtFabricante.getText());
        emitir.setEqpModelo(txtModelo.getText());
        emitir.setEqpSerie(txtNserie.getText());
        emitir.setDefeito(txtTelaOsDefeito.getText());
        emitir.setServico(txtTelaOsServico.getText());
        emitir.setIdProduto(Integer.parseInt(txtBuscarProdutId.getText()));
        emitir.setIdFuncionario(Integer.parseInt(txtTelaOsTec.getText()));
        emitir.setDescricao(jtxDescOS.getText());
        emitir.setValor(Float.parseFloat(txtValorOS.getText()));
        emitir.setGarantia((String)jcbTelaOsGarantia.getSelectedItem());
        emitir.setData(txtTelaOsData.getText());
                
        //criando o objeto
        OsDAO dao = new OsDAO();
        try {
            dao.emitirOs(emitir);
            txtBuscarProdutId.setText("");
            txtDescricao.setText("");
            txtFabricante.setText("");
            txtModelo.setText("");
            txtNserie.setText("");
            txtTelaOSNumOS.setText("");
            txtTelaOSPesquisaIdCli.setText("");
            txtTelaOsData.setText("");
            txtTelaOsDefeito.setText("");
            txtTelaOsPesquisaNomeCliente.setText("");
            txtTelaOsServico.setText("");
            txtTelaOsTec.setText("");
            txtValorOS.setText("");
            jtxDescOS.setText("");
                        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        }  
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        // Restriçao de Botoes
        btnSalvar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnDelete.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        Os p = new Os();
        OsDAO pdao = new OsDAO();
                    
        p.setTipoOs(tipo);
        p.setStatus((String) jcbTelaOsStatus.getSelectedItem());
        p.setIdCliente(Integer.parseInt(txtTelaOSPesquisaIdCli.getText()));
        p.setEqpDesc(txtDescricao.getText());
        p.setEqpFabric(txtFabricante.getText());
        p.setEqpModelo(txtModelo.getText());
        p.setEqpSerie(txtNserie.getText());
        p.setDefeito(txtTelaOsDefeito.getText());
        p.setServico(txtTelaOsServico.getText());
        p.setIdProduto(Integer.parseInt(txtBuscarProdutId.getText()));
        p.setIdFuncionario(Integer.parseInt(txtTelaOsTec.getText()));
        p.setDescricao(jtxDescOS.getText());
        p.setValor(Float.parseFloat(txtValorOS.getText()));
        p.setGarantia((String) jcbTelaOsGarantia.getSelectedItem());
        p.setData(txtTelaOsData.getText());
        p.setId(Integer.parseInt(txtTelaOSNumOS.getText()));
                
        try {
            pdao.updateOs(p);
            //JOptionPane.showMessageDialog(null, "Editado com sucesso!");
            // Apaga Campos ao Editar
            txtBuscarProdutId.setText("");
            txtDescricao.setText("");
            txtFabricante.setText("");
            txtModelo.setText("");
            txtNserie.setText("");
            txtTelaOSNumOS.setText("");
            txtTelaOSPesquisaIdCli.setText("");
            txtTelaOsData.setText("");
            txtTelaOsDefeito.setText("");
            txtTelaOsPesquisaNomeCliente.setText("");
            txtTelaOsServico.setText("");
            txtTelaOsTec.setText("");
            txtValorOS.setText("");
            jtxDescOS.setText("");
                        
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Erro ao editar!" +e);
        }
                 
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        // Restriçao de Botoes
        btnSalvar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnDelete.setEnabled(false);
        btnCancelar.setEnabled(false);

        Os p = new Os();
        OsDAO pdao = new OsDAO();
        p.setId(Integer.parseInt(txtTelaOSNumOS.getText()));
        try {
            pdao.delete(p);
            txtBuscarProdutId.setText("");
            txtDescricao.setText("");
            txtFabricante.setText("");
            txtModelo.setText("");
            txtNserie.setText("");
            txtTelaOSNumOS.setText("");
            txtTelaOSPesquisaIdCli.setText("");
            txtTelaOsData.setText("");
            txtTelaOsDefeito.setText("");
            txtTelaOsPesquisaNomeCliente.setText("");
            txtTelaOsServico.setText("");
            txtTelaOsTec.setText("");
            txtValorOS.setText("");
            jtxDescOS.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Restriçao de Botoes
        btnSalvar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnDelete.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        // Limpar os campos
            txtBuscarProdutId.setText("");
            txtDescricao.setText("");
            txtFabricante.setText("");
            txtModelo.setText("");
            txtNserie.setText("");
            txtTelaOSNumOS.setText("");
            txtTelaOSPesquisaIdCli.setText("");
            txtTelaOsData.setText("");
            txtTelaOsDefeito.setText("");
            txtTelaOsPesquisaNomeCliente.setText("");
            txtTelaOsServico.setText("");
            txtTelaOsTec.setText("");
            txtValorOS.setText("");
            jtxDescOS.setText("");
           

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtTelaOsTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelaOsTecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelaOsTecActionPerformed

    private void jTTelaOSPesquisaInfoCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTelaOSPesquisaInfoCliMouseClicked
        // TODO add your handling code here:
        //chamando o metodo setar campos
        setarCampos();
        


    }//GEN-LAST:event_jTTelaOSPesquisaInfoCliMouseClicked

    private void txtTelaOsPesquisaNomeClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelaOsPesquisaNomeClienteKeyReleased
        // TODO add your handling code here:
        //chamando o metodo de pesquisa de cliente
        pesquisarCliente();
    }//GEN-LAST:event_txtTelaOsPesquisaNomeClienteKeyReleased

    private void jrbTelaOsOracamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTelaOsOracamentoActionPerformed
        // TODO add your handling code here:
        tipo = "Orcamento";
    }//GEN-LAST:event_jrbTelaOsOracamentoActionPerformed

    private void jrbTelaOSOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTelaOSOSActionPerformed
        // TODO add your handling code here:
        tipo = "Ordem de Servico";
    }//GEN-LAST:event_jrbTelaOSOSActionPerformed

    private void jcbTelaOsStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTelaOsStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTelaOsStatusActionPerformed

    private void btnAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdutoActionPerformed
        // TODO add your handling code here:
        TeladeOs_BuscarProduto addProduto = new TeladeOs_BuscarProduto();
        addProduto.setVisible(true);
    }//GEN-LAST:event_btnAddProdutoActionPerformed

    private void txtDescricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyTyped
        // Limitando Caracteres
        int limite=25;
        if(txtDescricao.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtDescricaoKeyTyped

    private void txtNserieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNserieKeyTyped
         // Limitando Caracteres
        int limite=20;
        if(txtNserie.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtNserieKeyTyped

    private void txtModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModeloKeyTyped
         // Limitando Caracteres
        int limite=20;
        if(txtModelo.getText().length()==limite){
            evt.consume();
        }
        
    }//GEN-LAST:event_txtModeloKeyTyped

    private void txtFabricanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFabricanteKeyTyped
         // Limitando Caracteres 
       int limite=20;
        if(txtFabricante.getText().length()==limite){
            evt.consume();
        }
         
    }//GEN-LAST:event_txtFabricanteKeyTyped

    private void txtTelaOsDefeitoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelaOsDefeitoKeyTyped
         // Limitando Caracteres
        int limite=45;
        if(txtTelaOsDefeito.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_txtTelaOsDefeitoKeyTyped

    private void txtTelaOsServicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelaOsServicoKeyTyped
         // Limitando Caracteres
        int limite=45;
        if(txtTelaOsServico.getText().length()==limite){
            evt.consume();
        }        
    }//GEN-LAST:event_txtTelaOsServicoKeyTyped

    private void txtTelaOsTecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelaOsTecKeyTyped
         // Limitando Caracteres
        int limite=45;
        if(txtTelaOsTec.getText().length()==limite){
            evt.consume();
        }    
    }//GEN-LAST:event_txtTelaOsTecKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
         // Puxa data do Pc para Sistema:
        java.util.Date data = new java.util.Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.MEDIUM);
        txtTelaOsData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void txtValorOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorOSActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:

        pequisarOs();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudaActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,"                                                                            OS GESTOR \n"
                                             + "Olá, precisa de ajuda?\n"
                                             +"\n"
                                             + "*Deseja salvar? Para isso primeiro preencha os campos abaixo em seguida salve o cadastro. \n"
                                             + "\n"
                                             + "*Deseja editar? Para isso é necessario que primeiro efetue a pesquisa,\n "
                                             + "selecione o funcionario para alteração e em seguinda faça a alteração de acordo com a necessidade.\n"
                                             + "\n"
                                             + "*Deseja excluir? Para excluir efetue a pesquisa pelo funcionario que deseja excluir, "
                                             
                                              + "selecione e exclua.\n "
                                             +"\n"
                                             +"*Deseja pesquisar? Para pesquisar digite no campo de pesquisa os dados desejados.\n"
                                             +"\n"
                                             +" *Digitou errado? basta acionar o botão limpar para limpar todos os campos.\n"
                                             +"\n");
    }//GEN-LAST:event_btnAjudaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         // Abre tela com Botoes desativados
        btnEditar.setEnabled(false);
        btnDelete.setEnabled(false);
        btnCancelar.setEnabled(false); 
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeladeOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeladeOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeladeOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeladeOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeladeOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnAjuda;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPPesquisa;
    private javax.swing.JPanel jPclassOs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTTelaOSPesquisaInfoCli;
    private javax.swing.JComboBox<String> jcbTelaOsGarantia;
    private javax.swing.JComboBox<String> jcbTelaOsStatus;
    private javax.swing.JRadioButton jrbTelaOSOS;
    private javax.swing.JRadioButton jrbTelaOsOracamento;
    private javax.swing.JToolBar jtbBarraFerramenta;
    private javax.swing.JTextArea jtxDescOS;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblFabricante;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNserie;
    private javax.swing.JLabel lblTelaOSNumOS;
    private javax.swing.JLabel lblTelaOSPesquisaIdCli;
    private javax.swing.JLabel lblTelaOSStatus;
    private javax.swing.JLabel lblTelaOsData;
    private javax.swing.JLabel lblTelaOsDefeito;
    private javax.swing.JLabel lblTelaOsDesc;
    private javax.swing.JLabel lblTelaOsGarantia;
    private javax.swing.JLabel lblTelaOsServico;
    private javax.swing.JLabel lblTelaOsTecnico;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel pnlEquipamento;
    public static javax.swing.JTextField txtBuscarProdutId;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNserie;
    private javax.swing.JTextField txtTelaOSNumOS;
    private javax.swing.JTextField txtTelaOSPesquisaIdCli;
    private javax.swing.JLabel txtTelaOsData;
    private javax.swing.JTextField txtTelaOsDefeito;
    private javax.swing.JTextField txtTelaOsPesquisaNomeCliente;
    private javax.swing.JTextField txtTelaOsServico;
    private javax.swing.JTextField txtTelaOsTec;
    private javax.swing.JFormattedTextField txtValorOS;
    // End of variables declaration//GEN-END:variables
}
