/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Conexao.ModuloConexao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;




/**
 *
 * @author Walleson Moura
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    
Connection conexao = null;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        btnSair = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        menuCad = new javax.swing.JMenu();
        menuCadUsuario = new javax.swing.JMenuItem();
        menuCadCliente = new javax.swing.JMenuItem();
        menuCadFuncionario = new javax.swing.JMenuItem();
        menuCadProduto1 = new javax.swing.JMenuItem();
        menuServico = new javax.swing.JMenu();
        menuServicoNovo = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        menuEstoqueControle = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menuRelatorioSPrestados = new javax.swing.JMenuItem();
        menuRelatorioPGastos = new javax.swing.JMenuItem();
        menRelCli = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuAjudaSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SO Gestor - Inicio");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setBackground(new java.awt.Color(153, 204, 255));
        desktop.setToolTipText("");

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/exit.png"))); // NOI18N
        btnSair.setText("Trocar Usuario");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addGap(0, 541, Short.MAX_VALUE)
                .addComponent(btnSair))
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addComponent(btnSair)
                .addGap(0, 444, Short.MAX_VALUE))
        );
        desktop.setLayer(btnSair, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Menu.setBorder(new javax.swing.border.MatteBorder(null));
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menuCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N
        menuCad.setText("Cadastros");
        menuCad.setEnabled(false);

        menuCadUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        menuCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/users.png"))); // NOI18N
        menuCadUsuario.setText("Usuario");
        menuCadUsuario.setEnabled(false);
        menuCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadUsuarioActionPerformed(evt);
            }
        });
        menuCad.add(menuCadUsuario);

        menuCadCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/client.png"))); // NOI18N
        menuCadCliente.setText("Cliente");
        menuCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadClienteActionPerformed(evt);
            }
        });
        menuCad.add(menuCadCliente);

        menuCadFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        menuCadFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/worker.png"))); // NOI18N
        menuCadFuncionario.setText("Funcionario");
        menuCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFuncionarioActionPerformed(evt);
            }
        });
        menuCad.add(menuCadFuncionario);

        menuCadProduto1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        menuCadProduto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/fornecedor.png"))); // NOI18N
        menuCadProduto1.setText("Fornecedor");
        menuCadProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadProduto1ActionPerformed(evt);
            }
        });
        menuCad.add(menuCadProduto1);

        Menu.add(menuCad);

        menuServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/service.png"))); // NOI18N
        menuServico.setText("Serviços");

        menuServicoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/service.png"))); // NOI18N
        menuServicoNovo.setText("Novo Serviço");
        menuServicoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServicoNovoActionPerformed(evt);
            }
        });
        menuServico.add(menuServicoNovo);

        Menu.add(menuServico);

        menuEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/products.png"))); // NOI18N
        menuEstoque.setText("Estoque");
        menuEstoque.setEnabled(false);
        menuEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEstoqueActionPerformed(evt);
            }
        });

        menuEstoqueControle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/control.png"))); // NOI18N
        menuEstoqueControle.setText("Controle");
        menuEstoqueControle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEstoqueControleActionPerformed(evt);
            }
        });
        menuEstoque.add(menuEstoqueControle);

        Menu.add(menuEstoque);

        menuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/report.png"))); // NOI18N
        menuRelatorio.setText("Relatorio");
        menuRelatorio.setEnabled(false);

        menuRelatorioSPrestados.setText("Serviços Prestados");
        menuRelatorioSPrestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioSPrestadosActionPerformed(evt);
            }
        });
        menuRelatorio.add(menuRelatorioSPrestados);

        menuRelatorioPGastos.setText("Produtos ");
        menuRelatorioPGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioPGastosActionPerformed(evt);
            }
        });
        menuRelatorio.add(menuRelatorioPGastos);

        menRelCli.setText("Clientes");
        menRelCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelCliActionPerformed(evt);
            }
        });
        menuRelatorio.add(menRelCli);

        jMenuItem1.setText("Fornecedores");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuRelatorio.add(jMenuItem1);

        jMenuItem2.setText("Funcionarios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuRelatorio.add(jMenuItem2);

        Menu.add(menuRelatorio);

        menuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Help.png"))); // NOI18N
        menuAjuda.setText("Ajuda");

        menuAjudaSobre.setText("Sobre+");
        menuAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAjudaSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(menuAjudaSobre);

        Menu.add(menuAjuda);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        setSize(new java.awt.Dimension(688, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // as linhas abaixo substituem a label lblData pela data atual do sistema ao ser inicializado
        //Date data = new Date();
       // DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
       // lblData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void menuCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadUsuarioActionPerformed
        // TODO add your handling code here:
        CadastroUsuario user = new CadastroUsuario();
                user.setVisible(true);

              
    }//GEN-LAST:event_menuCadUsuarioActionPerformed

    private void menuCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadClienteActionPerformed
        // TODO add your handling code here:
         
                //visualizar tela de cadastro de clientes
        CadastroCliente cliente = new CadastroCliente();
                cliente.setVisible(true);
    }//GEN-LAST:event_menuCadClienteActionPerformed

    private void menuCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFuncionarioActionPerformed
        // TODO add your handling code here:
        
        CadastrarFuncionario funcionario = new CadastrarFuncionario();
                funcionario.setVisible(true);
        
        
    }//GEN-LAST:event_menuCadFuncionarioActionPerformed

    private void menuEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEstoqueActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuEstoqueActionPerformed

    private void menuServicoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServicoNovoActionPerformed
        // TODO add your handling code here:
        TeladeOS os = new TeladeOS();
        os.setVisible(true);
        
    }//GEN-LAST:event_menuServicoNovoActionPerformed

    private void menuEstoqueControleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEstoqueControleActionPerformed
        // TODO add your handling code here:
         EstoqueCadastrarProduto cadprodutos = new EstoqueCadastrarProduto();
                cadprodutos.setVisible(true);
        
    }//GEN-LAST:event_menuEstoqueControleActionPerformed

    private void menRelCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelCliActionPerformed
        // TODO add your handling code here:
        // Gerando Relatório de Cliente---> Wanderson
        
int confirma = JOptionPane.showConfirmDialog(null, "Confirmar a impressão deste relatório?", "Atenção",JOptionPane.YES_NO_OPTION);
if(confirma == JOptionPane.YES_NO_OPTION){
    
    //Imprimindo o relatorio com o framwork jasperReports
    
    try{
        //Usando a classe jasperprint para preparar a impressão de um relatório
        JasperPrint print = JasperFillManager.fillReport("C:\\reports/Clientes.jasper", null,conexao);
        // a linha abaixo exibe o relatório através da classe jasperViewer
        JasperViewer.viewReport(print,false);
    }catch (Exception e){
        JOptionPane.showConfirmDialog(null, e);
        
    
}
}
    }//GEN-LAST:event_menRelCliActionPerformed

    private void menuCadProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadProduto1ActionPerformed
        // TODO add your handling code here:
        CadastroFornecedor telaFornecedor = new CadastroFornecedor();
        telaFornecedor.setVisible(true);
    }//GEN-LAST:event_menuCadProduto1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int confirma = JOptionPane.showConfirmDialog(null, "Confirmar a impressão deste relatório?", "Atenção",JOptionPane.YES_NO_OPTION);
if(confirma == JOptionPane.YES_NO_OPTION){
    
    //Imprimindo o relatorio com o framwork jasperReports
    
    try{
        //Usando a classe jasperprint para preparar a impressão de um relatório
        JasperPrint print = JasperFillManager.fillReport("C:\\reports\\Fornecedor.jasper", null,conexao);
        // a linha abaixo exibe o relatório através da classe jasperViewer
        JasperViewer.viewReport(print,false);
        
    }catch (Exception f){
        
        JOptionPane.showConfirmDialog(null, f);
    }
}
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
                                                  
      
        int confirma = JOptionPane.showConfirmDialog(null, "Confirmar a impressão deste relatório?", "Atenção",JOptionPane.YES_NO_OPTION);
    if(confirma == JOptionPane.YES_NO_OPTION){
    
    //Imprimindo o relatorio com o framwork jasperReports
    
    try{
        //Usando a classe jasperprint para preparar a impressão de um relatório
        JasperPrint print = JasperFillManager.fillReport("C:\\reports\\Funcionarios2.jasper", null,conexao);
        // a linha abaixo exibe o relatório através da classe jasperViewer
        JasperViewer.viewReport(print,false);
        
    }catch (Exception g){
        
        JOptionPane.showConfirmDialog(null, g);
    
}
    }                                          
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuRelatorioPGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioPGastosActionPerformed
        
        // Mensagem para confirmar abertura do relatorio
        
        int confirma = JOptionPane.showConfirmDialog(null, "Confirmar a impressão deste relatório?", "Atenção",JOptionPane.YES_NO_OPTION);
     if(confirma == JOptionPane.YES_NO_OPTION){
    
    //Imprimindo o relatorio com o framwork jasperReports
    
    try{
        //Usando a classe jasperprint para preparar a impressão de um relatório
        JasperPrint print = JasperFillManager.fillReport("C:\\reports\\Produtos.jasper", null,conexao);
        // a linha abaixo exibe o relatório através da classe jasperViewer
        JasperViewer.viewReport(print,false);
        
    }catch (Exception h){
        
        JOptionPane.showConfirmDialog(null, h);
    }

    }            
                                                       

    }//GEN-LAST:event_menuRelatorioPGastosActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        //feixa a tela
        this.dispose();
        TelaLogin logoff = new TelaLogin();
        logoff.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void menuRelatorioSPrestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioSPrestadosActionPerformed
        // Mensagem para confirmar abertura do relatorio

        int confirma = JOptionPane.showConfirmDialog(null, "Confirmar a impressão deste relatório?", "Atenção",JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_NO_OPTION){

            //Imprimindo o relatorio com o framwork jasperReports

            try{
                //Usando a classe jasperprint para preparar a impressão de um relatório
                JasperPrint print = JasperFillManager.fillReport("C:\\reports\\OS.jasper", null,conexao);
                // a linha abaixo exibe o relatório através da classe jasperViewer
                JasperViewer.viewReport(print,false);

            }catch (Exception h){

                JOptionPane.showConfirmDialog(null, h);
            }

        }

    }//GEN-LAST:event_menuRelatorioSPrestadosActionPerformed

    private void menuAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAjudaSobreActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"\n"
                                             +"OS Gestor é uma ferramenta desenvolvida pelos academicos para atender \n"
                                             +" usuários que necessitam gerenciar serviços. O sistema com versão única. \n"
                                             +"\n"+"\n"+"\n"
                                             +"Desenvolvido em 2016"
                                              );
    }//GEN-LAST:event_menuAjudaSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton btnSair;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem menRelCli;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuItem menuAjudaSobre;
    public static javax.swing.JMenu menuCad;
    private javax.swing.JMenuItem menuCadCliente;
    private javax.swing.JMenuItem menuCadFuncionario;
    private javax.swing.JMenuItem menuCadProduto1;
    public static javax.swing.JMenuItem menuCadUsuario;
    public static javax.swing.JMenu menuEstoque;
    private javax.swing.JMenuItem menuEstoqueControle;
    public static javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenuItem menuRelatorioPGastos;
    private javax.swing.JMenuItem menuRelatorioSPrestados;
    private javax.swing.JMenu menuServico;
    private javax.swing.JMenuItem menuServicoNovo;
    // End of variables declaration//GEN-END:variables
}
